# squoia/MT_systems/squoia/esqu/morphgen_foma/Makefile
# This makefile requires GNU Make.

unificadoTransfer.fst: unificadoTransfer.foma
	foma -f $<

clean:
	rm -f *.fst

.PHONY: clean

# end squoia/MT_systems/squoia/esqu/morphgen_foma/Makefile
