# clean latex directory before committing!
clean:
	rm -f	*.aux
	rm -f	*.log
	rm -f	*.dvi
	rm -f	*.ps
	rm -f	*.toc
	rm -f	*.bbl
	rm -f	*.blg
	rm -f	*.xdv
	rm -f	*.out
	rm -f	*.url
	rm -f	*.lof
	rm -f	*.lot
	rm -f	*.bck
	rm -f	*.backup
	rm *~
