main /mnt/storage/hex/projects/clsquoia/arios_squoia_git/morphology/normalizer/normalizer.fst
spanish /mnt/storage/hex/projects/clsquoia/arios_squoia_git/morphology/normalizer/spanish.fst
main2 /mnt/storage/hex/projects/clsquoia/arios_squoia_git/morphology/normalizer/normalizer-relax.fst
spanish2 /mnt/storage/hex/projects/clsquoia/arios_squoia_git/morphology/normalizer/spanish-relax.fst
guesser /mnt/storage/hex/projects/clsquoia/arios_squoia_git/morphology/normalizer/guesser.fst

main
spanish
main2
spanish2
guesser