read regex [ 

! 1.1 
"1SG.A":{no} "=pour":{sai} "=Verb":0 "-EP":t "-PROG":{aty} "-IRR":e "=3n.m.O":{ro} 				!nosaitatyero
| "water":{nihaa} "+Noun":0 

! 1.2 
| "2S":p "=look.for":{amin} "=Verb":0 "-IRR":e 										!pamine
| "stone":{mapi} "+Noun":0 

! 1.3 
| "later":{apaata} "+Adverb":0 
| "1SG.A":{no} "=make":{vetsik} "=Verb":0 "-EP":a "-DIST":{ye} "-EP":t "-DIR":{av} "-PRF":{ak} "-IRR":e "=OPT":{ta} 
| "3n.m.poss":o "=hole":{morona} "+Noun":0 

! 1.4 
| "NEG.IRR":{airo} "=COND":{rika} 
| "3m.A":i "=kill":{tsoNk} "=Verb":0 "-EP":a "-PL":{he} "-EP":t "-PRF":{ak} "-REGR":a "-IRR":e "=CNT.F":{mi} 

! 1.5 
| "when/if":{arika} 
| "3m.A":i "=see":{ny} "=Verb":0 "-PRF":{ak} "-IRR":e "=3n.m.O":{ro} 
| "1PL.S":a "=plant":{paNki} "=Verb":0 "-EP":t "-IRR":e 
| "manioc":{kaniri} "+Noun":0 
| "3m.A":y "=bring":{am} "=Verb":0 "-PRF":{ak} "-REAL":e "=3m.O":{ri} 
| "3m.poss":i "=cow":{vaaka} "+Noun":0 "-poss":{te} 

! 1.6 
| "3m.S":i "=come":{ken} "=Verb":0 "-REAL":i 
| "3m.A":i "=teach":{vamet} "=Verb":0 "-REGR":a "-IRR":e "=3m.O":{ri} 
| "in.order":{oNkaNtya} 
| "3m.A":y "=help":{amitako} "=Verb":0 "-EP":t "-IRR":e "=3m.O":{ri} 

! 1.7 
| "1SG.S":{no} "=want":{kov} "=Verb":0 "-PROG":{atz} "-REAL":i 
| "1SG.S":{no} "=plant":{paNki} "=Verb":0 "-EP":t "-IRR":e 
| "papaya":{mapocha} "+Noun":0 

! 1.8 
| "NEG.REAL":{te} 
| "1SG.S":{no} "=like":{nimo} "=Verb":0 "-AUG":{piro} "-EP":t "-IRR":{ia} 
| "1SG.S":{no} "=get.drunk":{shiNki} "=Verb":0 "-AUG":{piro} "-EP":t "-IRR":{ia} 

! 1.9 
| "be.necessary":{ontzimatye} 
| "work":{aNt} "-EP":a "-DUR":{vai} "-EP":t "-IRR":e 
| "all":{maaro} "<AUG>":{ite} "ADV":{ni} 

! 1.10 
| "3n.m.A":o "=IRR":N "-bathe":{kaa} "=Verb":0 "-EP":t "-PRF":{ak} "-IRR":e "=3.O":{ni} "=3m.O":{ri} 
| "3n.m.A":o "=IRR":N "-cook":{kotsi} "-EP":t "-IRR":e "=3O":{ni} "=3n.m.O":{ro} 
| "her.food":"oyari" 

! 1.11 
| "3m.A":i "=be.strong":{shintsi} "-BEN":{viNt} "-PRF":{ak} "-REAL":i "=1SG.O":{na}
| "1SG.A":n "=take":{ay} "-IRR":e "=3m.O":{ri} 
| "man":{shiraNpari} "=DEM":{ka} 

! 1.12 
| "3m.A":i "=kill":v "-CAUS":{ak} "-PRF":{ak} "-REAL":i "=1SG.O":{na} "=3m.O":{ri} 
| "DEM":{iyoka} 

! 1.13 
| "1SG.S":{no} "=go":{ha} "-EP":t "-DIR":{an} "-PRF":{ak} "-REAL":i "=ADV.P":{raNki} 

! 1.13 REPEATED INDEX 
| "2A":{pi} "=say":{kaNt} "-IRR":e "=1SG.O":{na} "=3n.m.O":{ro} 

! 1.14 
| "come.on":{tsamea} 
| "1PL.S":a "=go":{ha} "-EP":t "-IRR":e 

! 1.15 
| "2S":{pi} "=IRR":m {pok} "=Verb":0 "-IRR":e "=ADV":{ra} 							!pimpokera

! 1.16 
| "3M.A":y "=take":{ay} "=Verb":0 "-REAL":i "=2.O":{mi}  "=APREH":{kari} 					!yayimikari

! 1.17 
| "2A":{pi} "=IRR":N "-send":{tyaNk} "-REGR":{ah} "-EP":a "-ICPL":{it} "-IRR":e "=1SG.O":{na} "=CNT.F":{mi} 

! 1.18 
| "NEG.IRR":{airo} 
| "2S":p "=look":{amin} "-EP":a "-DUR":{vai} "~EP.REAL":{tzitzi}

! 1.19 
| "go":{ha} "-EP":t "-REGR":{ah} "-REAL":a "=1SG.O":{na} 

! 1.20 
| "but":{iro}
| "crawl":{kamatsa} "-DUR":{vai} "-EP":t "-PRF":{ak} "-REAL":i "=1SG.O":{na} 

! 1.21 
| "1SG.poss":{no} "=husband":{ime} 
| "NEG.REAL":{te} 
| "3m.S":i "=be.at":{saik} "-IRR":e 
| "3m.S":i "=go":{ha} "-EP":{tz} "-REAL":i 
| "3m.S":y "=work":{aNt} "-EP":a "-DUR":{vai} "-EP":{tz} "-REAL":i 
| "3m.S":i "=cut":{tot} "-PROG":{atz} "-REAL":i 
| "rubber.tree":{shiringa} 

! 1.22 
| "3n.m.S":o "=be.at":{saik} "-PROG":{atz} "-REAL":i "=ADV":{ka} 
| "company":{compañia} 
| "NEG.REAL":{te} 
| "3m.S":i "=allow":{shini} "-EP":t "-IRR":e "=3n.m.O":{ro} 
| "make":{aNt} "IRR":e 
| "1PL.poss":a "=garden":{vani} "-PL":{paye} 
| "other.side":{intatzikero} 
| "NEG.REAL":{te} 
| "3m.A":i "=allow":{shini} "-EP":t "-IRR":e "=3n.m.O":{ro} 
| "make":{aNt} "IRR":e 
| "1PL.poss":a "=garden":{vani} 
| "1PL.S":a "=IRR":N "-plant":{paNki} "-EP":t "-IRR":e 
| "plantain":{parentzi} 
| "manioc":{kaniri} 

! 1.23 
| "when":{arika} 
| "3m.A":i "=see":{ny} "-PRF":{ak} "-IRR":e "=3n.m.O":{ro} 
| "1PL.S":a "=plant":{paNki} "-EP":t "-IRR":e 
| "manioc":{kaniri} 
| "3m.A":y "=bring":{am} "-PRF":{ak} "-IRR":e "=3m.O":{ri} 
| "3m.poss":i "=cow":{vaaka} "-poss":{te} 
| "3m.A":i "=finish":{tsoNki} "-REAL":i "=3n.m.O":{ro} 
| "3m.A":y "=eat":ov "-REAL":a "=3n.m.O":{ro} 
| "all":{maaroni} 
| "1PL.A":a "=eat":v "-CAUS":{aka} "-IRR":{ia} "=3m.O":{ri} "=REL":{ri} "=CNT.F":{mi} 
| "1SG.poss":n "=child":{eentsi} "-poss":{te} "-DIM":{patsaini} ! neentsitpatsaini / n=eentsi-te-patsaini 

! 1.24 
| "1PL.poss":a "=word":{nyaa} "-poss"{ni} "=DEM":{Nta} 
| "1PL.A":a "=know":{yo} "-FRUS":{ve} "-EP":t "-REAL":a "=3n.m.O":{ro} 
| "1PL.poss":a "=word":{nyaa} "-poss":{ni} 
| "only":{intaani} 
| "1PL.poss":a "=son":{tomi} "-PL":{paye} 
| "NEG.REAL":{te} 
| "3m.A":i "=know":{yo} "-EP":t "-REGR":{ah} "-IRR":e "=3n.m.O":{ro} 
| "3m.A":i "=speak":{nyaa} "-DUR":{vai} "-EP":t "-REGR":{ah} "-IRR"e "=3n.m.O":{ro} 
| "1PL.poss":a "=word":{nyaa} "-poss":{ni} 

! 2.1 
! ivenki ‘his magic plant’
! ovinkiri ‘she jumped into the river’ 
! shaveta ‘butterfly’
! pivito ‘your canoe’ 
! netsi ‘louse’ 
! pinitsi ‘magic plant’ 

! 2.2 
! iyomitairi [ɪjomɪteʲɾɪ] ‘he teaches them’ 
! ivairo[ɪßeʲro] ‘his name’ 
! airo [eʲro] ‘negative irrealis marker’ 
! itsipatairo[ɪtsʰipateʲro] ‘he combines it’ 

! 2.3 
! oka ‘this’ 
! aka ‘here’ 
! hiri ‘here it is’ 
! ari ‘that’s alright’ 
! ero ‘negative irrealis’ 
! iro ‘but, nevertheless’

! 2.4 
! piri[pɪɾɪ] ‘your father’ 
! piiri[pɪ:ɾɪ] ‘bat’ 
! sari[saɾɪ] ‘parrot’ 
! saari [sa:ɾɪ] ‘opossum’ 
! ora [oɾa] ‘that’ 
! oori[o:ɾɪ] ‘bird species’ 
! entyo[entʲo] ‘woman’s sister’ 
! eentsi[e:nʦʰɪ ̥ ] ‘child’ 

! 2.5 
| "1SG.A":{no} "=see":{ny} "-PROG":{atz} "-REAL":i "=3n.m.O":{ro} 
| "big":{aNtaro} "=EXCL":{ve} 

! 2.6 
| "1SG.poss":{no} "=daughter":{shiNto} 
| "EXIST":{tzimatsi} 
| "2A":{pi} "=want":{niNta} "-REAL":{a} "-AUG":{ni} 

! 2.7 
| "1PL.S":a "=IRR":N "-bathe.in.steam":{tyooNk} "-APPL.REAS":{aNt} "-IRR":{ia} "=REL":{ri} 

! 2.8 
| "1SG.S":{no} "=IRR":N "-cut":{chek} "-IRR":{ia} 

! 2.8 REAPEATED
! no.kai.ma.vai.tzi ‘I kept groaning’   
! ki.tai.ri.ki‘peccary’
! ai.sa.tzi ‘also’
! no.sai.ki‘I was in it’
! iN.pa.kai‘he will give us’

! 2.9 
! in.tsoN.poi ‘inside’
! i.tsa.noi.ri.ki ‘his string of beads’ 
! tsoi.ro.ki‘snail species’ 
! oi.rik ‘to tie’ 

! 2.10 
| "NEG.REAL":{te} 
| "3m.S":i "=know":{yo} "-EP":t "-IRR":e 

! 2.11 
| "NEG.REAL":{te} 
| "3n.m.S":o "=want":{niNt} "-IRR":e 
| "3n.m.S":o "=IRR":N "-get.soiled":{kipatsi} "-EP":t "-IRR":e 

! 2.12 
| "NEG.REAL":{te} 
| "1PL.A":{amit} ".be. accustomed-CUST":{apiNt} "-IRR":{ia} "=3n.m.O":{ro} !REVISE 
| "drink":{ir} "-CUST":{apiNt} "-IRR":e "=REL":{ri} 
| "milk": {irichi} 

! 2.13 
| "2A":p "=split":{inchakota} "-IRR":e "=1SG.O":{na} 

! MISSING 2.14 - 2.17

! 2.18 
| "3m.A":i "=transform":{pi} "-REAL":i "=3m.O":{ri} 

! 2.19 
| "3m.S":i "=transform":{pi} "-DIR":{an} "-PRF":{ak} "-REAL"a 

! 2.20 
! -tsapaki ‘finger’   
! tsapyaki ‘on the river bank’   
! tampatsika ‘be vertical’  
! tampyaa ‘wind’ 
! paryantsi ‘plantain’    
! pyarentsi ‘masato [manioc beer]’

! 2.21 
! paamaNto‘burned wood’  
! pantyo‘duck’ 
! notaapi ‘my back’  
! tyaapa ‘chicken’
! =ta‘subjunctive clausal enclitic’  
! =tya‘emphatic clausal enclitic’ 

! 2.22 
| "3m.A":i "=carry":{ki} "-REAL":i "=3m.O":{ri} 

! 2.23
| "3m.A":i "=carry":{ki} "-DIR":{an} "-PRF":{ak} "-REAL":i "=1SG.O":{na} 

! 2.24 
! nasaNkaniki   [nasaŋganɪkɪ]  ‘in my heart’ 
! kityoNkari  [kɪtʲoŋgaɾɪ]   ‘red’ 
! opaNkita   [opaŋgɪta]   ‘it is planted’ 
! katoNkosatzi   [katoŋgosatsɨ]  ‘people from upriver’ 
! nairikaka   [naɪɾɪgaka]   ‘I held on (to the tree)’ 
! nochekakiro   [noʧegakɪɾo]   ‘I cut it’ 
! naaka    [na:ga]   ‘I’ 

! 2.25 
! kyaarontsi  ‘winter’  
! inkaari‘rain’ 
! kyaaryo‘it’s true!’    
! kaari‘negative copula’ 
! =kya‘emphatic enclitic’   
! =ka‘interrogative clausal enclitic’ 

! 2.26 
! tzina ‘palm sp.’(camonilla)  
! tsinani ‘girl’
! tzivana‘pineapple’  
! tsiva‘tree sp.’ (copal; Bursera odorata) 
! tziNkotsi ‘tail’    
! tsiNt ‘to urinate’ 

! 2.27 
! /ʧ/-/tsʰ/  chomeNta‘fish sp.’    
! tsomoNte ‘a bulge’ 
! /ʧ/-/tʲ/  kachori‘salted’    
! katyori‘acidic, sour’
! /tsʰ/-/tʲ/  ipitsoki‘he was turning around’  
! ipityoki‘his little thing’ 

! 2.28 
! samani ‘paca (rodent sp.)’  
! shametzi ‘pal; namesake’ 
! kasaNto‘bird species’  
! ashaniNka‘our fellowman’ 
! saNkina‘to write’  
! shiNki ‘corn’

! 2.29 
! /n/ vs. /m/  
! kanai‘Long John tree’   
! kamaantsi ‘phlegm’ 
! 
! kin ‘to pass’    
! kim ‘to hear, listen’ 

! 2.30 
! /n/ vs. /ɲ/  
! naakero‘I’ll bring it’ 
! nyaakiro‘I’ve seen it’
! 
! kona ‘to fish with 
! barbasco’  konya‘to appear’ 

! 2.31 
! onaNpi[o.nam.pi] ‘her village’  
! mapi[ma.pɪ] ‘stone’ 
! kasaNto[ka.san.to] ‘bird sp.’  
! onatoto[o.na.to.to] ‘cousin’ 
! katoNko[ka.toŋ.ko] ‘upriver’  
! nako[na.ko]‘my arm’ 

! 2.32 
! piryoki ‘grub’  
! pirota‘ball’ 
! paryantsi ‘plantain’  
! parari ‘otter’ 

! 2.33 
! kavana  [kawana] ‘tree sp.’  
! tzivi [tsɨß ̞ ɪ]  ‘salt’ 
! avavatzi [awaʋatsi] ‘we are eating’  
! vatsatsi  [watsʰatsʰɪ ̥ ]  ‘meat’ 
! ovakera  [owakeɾa] ‘recently’
! kovitsi  [ko ß ̞ itsʰe]  ‘pot’ 

! 2.34 
! a.bol.sa‘bag’		bo.ri.sa‘bag’ 
! b. pa.pel‘paper’	pa.pe.ri ‘paper’ 
! c. le.che‘milk’		i.ri.chi‘milk’ 
! d. pas.ti.lla‘pill’	pa.shi.tya‘pill’ 
! e. pe.lo.ta‘ball’	pi.ro.ta‘ball’ 
! f. hos.pi.tal‘hospital’	o.si.pi.ta.ri
! g. re.loj ‘watch’	no.re.ro.te ‘my watch’ 
! h. a.rroz ‘rice’	a.ro.so ‘rice’ 

! 2.35 
! CVV.CV.CV.CV  	poi.ni.ro.tsa  	[poɪnɪɾotsʰa]  	‘yacón (tree sp.)’ 
! V.CV    	a.ri   		[aɾɪ]   		‘positive polarity verb’ 
! VV.CV   	ai.sa.tzi  	[aɪsatsɨ]  	‘also’ 
! VN.CV   	in.cha   	[ɪnʧa]   	‘plant’ 
! VN.CVN.CVV  	in.tsoN.poi  	[ɪntsʰompoi]  	‘inside’ 
! CVVN.CVVN.CV  	tyooN.kaan.tsi 	[tʲoŋka:ntsʰɨ]  	‘to bathe in steam’

! 2.36 
| "3m.A":y "=leave":{ook} "-IMP.P":{ai} "-EP":t "-REAL":a "=1SG.O":{na} 

! 2.37 
| "1SG.S":{no} "=call":{kaim} "-EP":a "-DUR":{vai} "-EP":{tz} "-REAL":i 

! 2.38 
| "1SG.A":n "=take":a "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 

! 2.39 
| "go":{ha} "-quickly":{ite} "-EP":t "-PRF":{ak} "-REAL":i 

! 2.40 
! a. CV.CV  ̍ hi.ri ‘here he is’ 
! b. V.CV  ̍ a.ri ‘positive polarity verb’ 
! c. V.CVV  i.̍ roo ‘she’ 
! d. CVV.CV  ̍ naa.ri ‘I also’

! 2.41 
! -Notomi, omapiro piposakiri paniri?
! -Son, is it true that you hit your cousin? 
! -Te, apaa.     
! -No, Dad.

! 2.42 
| "3n.m.A":o "=hit":{pos} "-PRF":{ak} "-REAL":i "=1SG.O":{na} 
| "1SG.poss":{no} "=head":{ito} "-LOC":{ki} 
| "IDEO":{poo}

! 2.43 
! ni.ˈhaa ‘water’   
! i.ˈroo  ‘she’ 
! 'niN.ka‘who’  
! taN.ˈpyaa  ‘wind’ 
! a.ˈka  ‘here’  
! ˈnaa.ka  ‘I’

! 2.44 
! shi.ˈma  ‘fish’    
! i.ˈsha ‘grandmother’ 
! tzi.ˈna   ‘palm sp.’   
! mi.ˈsha ‘naked tree (capirona)’
! shi.̍  na   ‘kapok tree’   
! tsi.ˈka  ‘where’   

! 2.45 
! o.ˈche.vo  ‘its branch’   
! ko.ˈshi.ri ‘monkey’ 
! ka.ˈme.tsa  ‘good’    
! paa.ˈma.ri ‘fire’ 
! pa.ˈshi.ni ‘other’    
! tzi.ˈva.na ‘pineapple’

! 2.46 
! ya.shi.ˈro.tsa.<te>   ‘his ax’ 
̩! i.va.ˈryan.tsi.<te.pa.ye>  ‘his plantains’ 
! no.̩ sai.ka.ˈhe.tzi.<ka>   ‘we are here’ 
̩! a.ka.̩ ra.he.ˈtai.ye.<ni>   ‘we all’

! 2.47 
! -Naakave!‘Hi! [I am]!’ 
! -Aviro!‘Hi! [you are]!’

! 2.48 
| "come.on":{tsame} "=ADV":{ra} "=EXCL":{ve} 

! 2.49 
| "3m.poss":i "=bow":{pyaameni} 
| "big":{aNtaro} "=EXCL":{ve} 

! 2.50 
| "3m.A":i "=plant":{paNki} "-EP":t "-CAUS":{ak} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "3m.poss":i "=corn":{shiNki} "-poss":{ni} 
| "3m.poss":i "=beans":{machaki} "-poss":{te} 
| "3m.poss":i "=manioc":{kaniri} 
| "3m.poss":i "=plantain":{paryantsi} "-poss":{te} "-PL":{paye} 
| "3m.poss":i "=coca":{koka} "-poss":{ni} 

! 2.51 
| "be.called":{pai} "-EP":t "-REAL":a 
| "3m.A":y "=look.for":{amin} "-REAL":i "=REL":{ri} 
| "police":{sararo} 
| "1SG.poss":{no} "=bag":{tsarate} "-LOC":{ki} 

! 2.52 
| "who":{niNka} 
| "come":{pok} "-STAT":{atsi} "=REL":{ri} "=Q":{ka} 

! 2.53 
| "3m.S":i "=go":{ha} "-EP":t "-PRF":{ak} "-REAL":i 
| "person’s.name":{Vela} 

! 2.54 
| "2A":{pi} "=want":{niNt} "-APPL":{ako} "-EP":t "-REAL":a "=1SG.O":{na} 
| "1SG.poss":{no} "=word":{nyaa} "-poss":{ni} 

! 2.55 
! LENITION OF P→W, K→J 
!   ‘my_’  ‘your _’  ‘his_’   ‘her_’   ‘our_’ 
! pitotsi‘canoe’  novito   pivito  ivito   ovito   avito 
! pava‘god’   novavani   pivavani  ivavani  ovavani  avavani
! koka ‘coca’    noyokani   piyokani  iyokani  yokani  yokani 
! kaniri ‘manioc’  noyaniri   piyaniri  iyaniri  yaniri   yaniri 
! kami‘rotten leaf’  noyamini   piyamini  iyamini  yamini  yamini 

! 2.56 
! LENITION OF K→Ø 
!   ‘my_’   ‘your_’  ‘his_’   ‘her_’   ‘our_’  
! kitsarentsi‘clothes’ noitsari   piitsari  iitsari   oitsari   aitsari
! kitzitsi ‘leg’   noitzi   piitzi   iitzi   oitzi   aitzi 
! kishitsi‘hair’  noishi   piishi   iishi   oishi   aishi
! kipatsi ‘land’  noipatsite   piipatsite  iipatsite  oipatsite   aipatsite
! kitsoki ‘egg’  noitsoki   piitsoki  iitsoki   oitsoki  aitsoki 

! 2.57 
| "3m.S":i "=grow":{shiNka} "-flesh":{vatsa} "-muscle":{pori} "-EP":t "-DIR":{an} "-REGR":{ah} "-REAL":i 

! 2.58
| "3n.m.S":o "=happen":{kaNt} "-EP":a "-FRUS":{vi} "-EP":t "-IRR":{ia} "=OPT":{ta} 

! 2.59 
| "1SG.S":n "=drink":{ir} "-EP":a "-DIST":{ye} "-EP":{tz} "-REAL":i 

! 2.60 
| "good":{kameetsa} "-EP":t "-PRF":{ak} "-IRR":e "=COND":{rika} 

! 2.61 
| "3m.S":i "=go":{ha} "-EP":{tz} "-REAL":i 
| "river":{pareni} "LOC":{ki} 

! 2.62 
| "3m.A":i "=like":{neve} "-EP":t "-REAL":a "=3n.m.O":{ro} 
| "3n.m.S":i "=IRR":{ha} "-go":t "-IRR":e ! REVISED
| "river":{pareni} "-LOC":{ki} 

! 2.63 
! VOWEL LOSS I, O, A→ØAT THE PROCLITIC-ROOT BOUNDARY
!   ‘my_’  ‘your_’  ‘his_’  ‘her_’  ‘our_’ 
! irantsi‘blood’  nirani  pirani  irani  irani  irani  
! oketsi‘eye’  noki  poki  [iroki] oki  oki 
! aikintsi ‘tooth’  naiki  paiki  [iraiki]  aiki  aiki

! 2.64 
! VOWEL LOSS NO →NAT THE PROCLITIC-ROOT BOUNDARY 
| "1SG.A":{no} "=take":a "-PRF":{ak} "-REAL"i "=3n.m.O":{ro} 

! 2.65 
! VOWEL LOSS PI →PAT THE PROCLITIC-ROOT BOUNDARY
| "2A":{pi} "=wait":{ooya} "-REGR":{ah} "-IRR"e "=1SG.O":{na} 

! 2.66 
! VOWEL SHORTENING I:→I  AT THE RPOCLITIC-ROOT BOUNDARY 
!    ‘my_’  ‘your_’  ‘his_’  ‘her_’  ‘our_’  
! iitontsi ‘head’   noito  piito  iito  oito  aito 
! iishintsi ‘hair’  noishi   piishi  iishi   oishi  aishi 

! 2.67 
! VOWEL LOSS A→Ø, I→Ø AT THE RPOCLITIC-ROOT BOUNDARY ! REVISED
! akiri‘nose’   nokiri  pikiri  ikiri  okiri  akiri
! ikentsi‘neck’   nokentsi  pikentsi  ikentsi  ikentsi  akentsi

! 2.68 
| "pass":{avis} "-PRF":{ak} "-REAL":i 
| "many":{osheki} 
| "year":{osarentsi} 

! 2.69 
| "2S":p "=pass":{avish} "-IRR":e 

! 2.70 
| "3n.m.A":o "=hit":{pos} "-PRF":{ak} "-REAL":i "=1SG.O":{na} 
| "wind":{taNpyaa} 

! 2.71 
| "1SG.A":{no} "=hit":{posh} "-REAL":i "=3n.m.O":{ro} 
| "stone":{mapi} 

! 3.1 
| "1SG.poss":{no} "=thigh":{pori} "-LOC":{ki} 
| "3m.A"y "=take":a "-IMP.P":{ai} "-EP":t "-PRF":{ak} "-REAL":i "=1SG.O":{na} 
| "here":{haka} 

! 3.2 
| "3n.m.S":o "=wash.a.lot":{kivakiva} "~EP":{tz} "-REAL":i 

! 3.3 
| "2S":{pi} "=speak":{nyaa} "-DUR":{vai} "-EP":t "-IRR":e 

! 3.4 
| "1SG.poss":n "=arm":{ako} "-LOC":{ki} 
| "break":{kar} "-PRF":{ak} "-REAL":i "=1S.O":na 

! 3.5 
| "long.ago":{pairani} 
| "1SGposs":{no} "=grandpa":{charini} "-poss":{te} 
| "3m.A":i "=call":{pai} "-EP":{tz} "-REAL":i "=3n.m.O" :{ro} 
| "river":{nihaa} 
| "name":{Meantarini} 

! 3.6 
| "1SG.poss":{no} "=head":{ito} "-LOC":{ki} 
| "IDEO":{poo} 

! 3.7 
| "3n.m.S.swim":{ama} "-disheveled.head":{menkotzi} "-DIST":{ye} "-EP":t "-PRF":{ak} "-REAL":i 

! 3.8 
| "go":{ha} "-quickly":{ite} "-EP":t "-PRF":{ak} "-REAL":i "=3n.m.O":0 

! 3.9 
| "3m.A":i "=listen":{kem} "-CAUS":{aka} "-DIM":{niNt} "-REAL":a "=3m.O":{ri} 

! 3.10 
| "3m.A":i "=say":{kaNt} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} 

! 3.11 
| "3n.m.S":o "=gather":{koye} "-CL:small.round":{ki} "-EP":t "-PRF"{ak} "-REAL":i 

! 3.12 
| "be.strong":{shintsi} "-ADV":{ni} 
| "not.yet":{tekira} "=OPT":{ta} 
| "3n.m.S":o "=IRR":N "-dark":{tsiteni} "-EP":t "-IRR":e "=OPT":{ra} 


! 3.13 
| "2S":{pi} "=be.strong":{shintsi} "-EP":t "-REGR":{ah} "-PROG":{aty} "-IRR":e "=ADV":{ra} 

! 3.14 
| "young.man":{evaNkari} 
| "EXIST":{tzimatsi} 
| "3m.poss":i "=be.strong":{shintsi} "-NMZ":{Nka} 

! 3.15 
| "be.strong":{shintsi} "-ADJ":{ri} 
| "3n.m.S":o "=be":{kaNt} "-REAL":a 
| "rope":{shivitsa} 

! 3.16 
| "3m.S":i "=be.in":{saik} "-EP":a "-PL":{he} "-EP":t "-DIR":{ap} "-PRF":{ak} "-REAL":i 
| "village’s.name":{Metaro} "-LOC":{ki} 

! 3.17 
| "3m.A":i "=CAUS":v "-go.down":{anii} "-EP":t "-DIR":{ap} "-PRF":{ak} "-REAL":i "=1SG.O":{na} 

! 3.18 
| "PP":{ari} 
| "3m.A":i "=CAUS":v "-go.down":{anii} "-EP":t "-REGR":{ah} "-IRR":e "=1SG.O":{na} 

! 3.19 
! MISSING

! 3.20 
| "3m.A":i "=pass":{kin} "-CAUS.SOC":{ak} "-DIR":{an} "-PRF":{ak} "-REAL"i "=1SG.O":{na} 
| "inside":{iNtakiro} "=ADV":{Nta} 

! Suffixes Table 6 - 10

! 3.21 
| "3m.A":i "=hit":{pos} "-EP":a "-DUR":{vai} "-FRUS":{ve} "-EP":t "-PRF":{ak} "-REAL":a "=1SG.O":{na} 

! 3.22 
| "2A":{pi} "=be.similar":{shiy} "-CAUS":{ak} "-APPL.INST":{aNt} "-once":{apaiNt} "-IRR":e "=3n.m.O":{ro} 

! 3.23 
| "EXIST":{tzimatsi} 
| "1SG.poss":n "=plant":{incha} "-CL:small.flexible":{shi} "-poss":{te} "-small.part.DIM":{patsaini} 

! 3.24 
| "1SG.A":{no} "=IRR":N "-heat":{tsiy} "-PRF":{ak} "-IRR":e "=3m.O":{ri} 
| "3m.poss"i "=foot":{itzi} "-LOC":{ki} "-small.part.DIM":{patsaini} 

! 3.25 
| "3m.A":i "=go":{ha} "-EP":t "-APPL.INT":{ashi} "-EP":t "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "3m.poss":i "=house":{paNko} "-CL:small.flexible":{shi} "-LOC":{ki} 

! 3.26 
| "3m.poss":i "=fear":{tsaro} "-NMZ":{Nka} "-LOC":{ki} "-DIM":{ni} 
| "3m.S":i "=be":{kaNt} "-EP":a "-PL":{he} "-EP":t "-PRF":{ak} "-REAL":i 

! 3.27 
| "be.morning":{kitaite} "-NMZ":{ri} "-LOC":{ki} "-PL":{paye} 

! 3.28 
| "1SG.poss":{no} "=husband":{imi} "-bunch":{poroki} "=DEM":{ra} 

! 3.29 
| "3n.m.S":o "=be.at":{saik} "-REAL":i "=ADV":{ra} 

! 3.30 
| "NEG.REAL":{te} "=ADV":{ra} 
| "1SG.A":{no} "=soul":{shiri} "-EP":t "-IRR":{ia} "=3n.m.O":{ro} 

! 3.31 
| "EXIST":{tzimatsi} 
| "1SG.poss":n "=plant":{incha} "-leaf":{shi} "-part":{patsa} "-DIM":{ini} 
| "1SG.A":{no} "=plant":{paNki} "-EP":{tz} "-REAL":i "=REL":{ri} "=ADV":{ra} 

! 3.32 
| "1SG.A":{no} "=place":v "-EP":a "-DIST":{ye} "-EP":{tz} "-REAL":i "=REL":{ri} 
| "plant":{incha} "-leaf":{leaf} 
| "1SG.A":{no} "=bathe":N "-EP":{kaa} "-APPL.REAS":t "-IRR":{aNt} "=3m.O":{ri} "=REL":{ri} 
| "be.sick":{mantsi} "-EP":a "-ADJ":{ri} 

! 3.33 
| "not.yet":{tekira} "=OPT":{ta} 
| "3m.A":y "=throw":{ook} "-IRR":e "=3n.m.O":{ro} "=OPT":{ta} 
| "3m.S":y "=be.accustomed":{amet} "-EP":a "-PL":{he} "-EP" "-REAL" "=REL" 
| "long ago":{pairani} 

! 3.34 
| "that.n.m.":{ora} "=G.FOC":{ve} 
| "3m.A":i "=say":{kaNt} "-IMP.P":{ai} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} "=ADV":{Nta} 
| "salt":{tzivi} 

! 3.35 
| "1SG.S":{no} "=IRR":N "-dress":{kitsa} "-EP":t "-DIR":{av} "-PRF":{ak} "-IRR":{ia} "=OPT":{ta} "=N.C.FOC":{tya} "=O.FOC":{kya} 

! 3.36 
| "2A":{pi} "=cut":{chek} "-IRR":e "=3m.O":{ro} 
| "plant":{incha} "-plank":{paNki} 
| "1SG.poss":{no} "=plot":{vani} "-LOC":{ki} "=ADV":{Nta} "=EXCL":{ve} 

! 3.37 
| "seem":{kimit} "-PRF":{ak} "-REAL":a 
| "1PL.poss":a "=plot.of.land":{vani} "=ADV.P":{raNki} 

! 3.38 
| "NEG.REAL":{te} 
| "I":{naaka} 
| "1SG.S":{no} "=IRR":N "-be.embarrassed":{pashiveNt} "-IRR":{ia} 

! 3.39 
| "NEG.REAL":{te} 
| "big":{aNtaro} "-AUG":{ite} 
| "take":{ay} "-IRR":e 

! 3.40 
| "one":{aparo} "<also>":{hatzi} "one":{ni} 

! 3.41 
| "all":{maaro} "<AUG>":{ite} "all":{ni} 

! 3.42 
| "1PL.S":a "=play":{nyaatsa} "-PL":{he} "-EP":t "-REAL":a "-PL":{ni} 

! 3.43 
| "3m.S":i "=escape":{shitov} "-PL":{aiy} "-REGR":{ah} "-REAL":i "-PL":{ni} 

! 3.44 
| "NEG.REAL":{te} 
| "3n.m.A":o "=IRR":N "-pay attention":kimisaNt "-IRR":e "=1SG.O":{na} 

! 3.45 
| "1SG.A":{no} "=IRR":N "-burn":{ta} "-DIR":{av} "-PRF":{ak} "-IRR":e "=3n.m.O":{ro} "=OPT":{ta} 
| "2poss":{pi} "=opossum":{saari} "-sole":{KoNta} "-poss":{te} 
| "2poss":{pi} "=foot":{itzi} 

! 3.46 
| "2A":p "=split" "-IRR" "=3n.m.O" 
| "2poss":{pi} "=foot":{itzi} "=DEM":{ra} 

! 3.47 
| "2A":p "=split":inchakota "-IRR":e "=1SG.O":{na} 

! 3.48 
| "3m.A":i "=cut":{tov} "-flesh":{vatsa} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} 
| "3m.poss":i "=thigh":{pori} 

! 3.49 
| "3m.S":i "=grow":{shiriNka} "-flesh":{vatsa} "-muscle":{pori} "-EP":t "-DIR":{an} "-REGR":{ah} "-REAL":i 

! 3.50 
| "1SG.poss":{no} "=wife":{ina} 
| "3n.m.S.cry":{iraira} "~EP":t "-DIR":{an} "-PRF":{ak} "-REAL":a 

! 3.51 
| "3m.A":i "=carry.load":{kyakya} "~EP":{t} "-PRF":{ak} "-REAL":i "=1SG.O":{na} 

! 3.52 
| "NEG.IRR":{airo} 
| "2A":{pi} "=come.back":{piyapiya} "~EP":t "-APPL.INT":{ashi} "-EP":t "-REAL":a "=3m.O":{ri} 

! 3.53 
| "1SG.A":{no} "=walk":{keken} "~REP":a "-EP":t "-CAUS.COM":{aka} "-REAL":i "=3m.O":ri 
| "at.night":{tsiteni} 

! 3.54 
!| "2A":p "=look.for":{aminamina} "~EP":t "-REP":a "-EP":{it} "-ICPL":e "-IRR" "=3m.O":{ri} "=ADV":{ra} ! REVISED

! 3.55 
| "2S":p "=look.for":{amin} "-EP":a "-ICPL":{it} "-IRR":e 
| "testicle":{katsariki} "-ABS":{ntsi} "-dark.water":{chaari} "-AUG":{ni} 

! 3.56 
| "NEG.IRR":{airo} 
| "2A":{pi} "=cook":{kotsi} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} 
| "meat":{vatsa} "-ABS":{tsi} "=DEM":{ra} 

! 3.57 
| "person":{atziri} "-PL":{paye} 
| "now":{ironyaaka} 
| "be.joyous":{kimoshi} "-ADJ":{ri} 
| "3m.S":i "=be":{kaNt} "-EP":{a} "-PL":{he} "-EP":t "-REAL":a "=EXCL":{vev} 

! 3.58 
| "2A":{pi} "=build":{vitsik} "-DIR":{an} "-REGR":{ah} "-IRR":e "=1SG.O":{na} "=3n.m.O":{ro} 
| "1SG.poss":{no} "=house":{paNko} 
| "1SG.A":{no} "=put":{v} "-APPL.REAS":{aNt} "-EP":{a} "-DIST":{ye} "-EP":t "-IRR":{ia} "=3n.m.O":{ro} "=REL":{ri} ! REVISED
| "1SG.poss":{no} "=adornment":{tsanoiriki} "-PL":{paye} 

! 3.59 
| "1SG.S":{no} "=want":{kov} "-PROG":{atz} "-REAL":i 
| "1SG.S":{no} "=IRR":N "-plant":{paNki} "-EP":t "-IRR":e "=CNT.F":{mi} 
| "papaya":{mapocha} 

! 3.60 
| "FOC":{irotaki} 
| "1SG.A":{no} "=CAUS":{v} "-pass":{avis} "-APPL.REAS":{aNt} "-REAL":a "=3n.m.O":{ro} "=REL":{ri} ! REVISED
| "1SG.S":n "=live":{any} "-APPL.REAS":{aNt} "-REAL":{a} "-NMZ":{ri} 
| "week":{shimaana} "-LOC":{ki} "-PL":{paye} 
| "moon":{kashiri} "-LOC":{ki} "-PL":{paye} 
| "day":{kitaiteri} "-LOC":{ki} "-PL":{paye} 

! 3.61 
| "before":{pairani} 
| "1SG.poss":{no} "=fellowman":{shaniNka} "-PL":{paye} 
| "3m.poss":i "=deity":{pava} "-poss":{ni} "-EP":t "-REAL":a "=3m.O":{ri} 
| "stone":{mapi} 

! 3.62 
| "1PL.A":a "=IRR":N "-annatto":{potsot} "-IRR":{ia} "=3n.m.O":{ro} 
| "annatto":{potsotzi} 

! 3.63 
| "1SG.S=want-REAL" 
| "1SG.S=IRR-vomit-IRR=CNT.F" 

! 3.64 
| "3m.A":y "=take":{ay} "-IRR":e "=2O":{mi} "=APPR":{kari} 
| "bear":{maini} 

! 3.65 
| "WH":{tsika} "=DUB":{ma} 
| "3n.m.S":o "=be.called":{pai} "-EP":t "-REAL":a "=EMPH":{tya} "=Q":{ka} 

! 3.66 
| "PP":{ari} 
| "3m.A":i "=M.CAUS":{mi} "-sit":{saik} "-REAL":i "=3m.O":{ri} 

! 3.67 
| "1SG.A":n "=CAUS.AGT.drink":{oi} "-EP":t "-PRF":{ak} "-IRR":e "=3m.O":{ri} 
| "other":{pashini} 
| "plant":{incha} "-leaf":{leaf} 

! 3.68 
| "FOC":{irotaki} 
| "3n.m.S":o "=CAUS.AGT":v "-pass":{avis} "-APPL.REAS":{ako} "-EP":t "-PRF":{ak} "-REAL":i "=3m.O"{ri} "=REL":{ri} 

! 3.69 
| "3m.A":i "=CAUS.AGT":v "-walk":{anii} "-EP":t "-DIR":{ap} "-PRF":{ak} "-REAL":i "=1SG.O":{na} 

! 3.70 
| "3m.A":y "=work":{aNt} "-EP":a "-DUR":{vai} "-EP":t "-CAUS.SOC":{ak} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 

! 3.71 
| "EXIST":{tzimatsi} 
| "3m.poss":i "=soldier":{sorano} "-poss":{te} "-PL":{paye} 
| "stand.guard-EP-APPL.BEN-REAL=3m.O=REL" 

! 3.72 
| "NEG.REAL" 
| "3m.A=IRR-kneel.down-APPL.PRES-EP-DIR-PRF-IRR=3m.O" 

! 3.73 
| "3m.A":i "=say":{kaNt} "-APPL":{ako} "-ICPL":{it} "-EP":{tz} "-REAL":i "=3m.O":{ri} 
| "one":{aparomi} 
| "monkey":{koshiri} 

! 3.74 
| "1Sg.A":{no} "=hide":{man} "-EP":a "-APPL.SEP":{pitsa} "-EP":t "-PROG":{aty} "-IRR":e "=3m.O":{ri} 

! 3.75 
| "be.sick":{mantsiya} "-ADJ":{ri} "=DEM":{ra} 
| "3m.S":i "=IRR":N "-come":{pok} "-IRR":e 
| "another":{pashini} 
| "another":{pashini} 
| "1SG.A":{no} "=bathe":{saa} "-EP":t "-APPL.INST":{aNt} "-REAL":a "=3m.O":{ri} "=REL":{ri} 

! 3.76 
| "1SG.poss":n "=dog":{otsitzi} "-poss":{te} 
| "NEG.REAL":{te} 
| "3m.S":y "=bite":{atsik} "-CUST":{aNt} "-IRR":e 

! 3.77 
| "3m.S":i "=kiss":niNtat "-RCP":{av} "-PRF":{ak} "-PROG":{aty} "-REAL":a 

! 3.78 
| "he":{iriro} 
| "3m.S":i "=cut":{tot} "-PRF":{ak} "-REAL.RFL":a 

! 3.79 
| "3m.A":i "=cut":{tot} "-PRF":{ak} "-REAL":i "=3O":{ni} "=3m.O":{ri} 
| "3m.poss":i "=hair":{ishi} 
| "3m.poss":i "=son":{tomi} 

! 3.80 
| "3m.S":i "=be.at":{saik} "-REAL":i 
| "3m.A":i "=accompany":{tsipat} "-REAL":a "=3n.m.O":{ro} 
| "3m.poss":i "=wife":{ina} 

! 3.81 
| "3n.m.A":o "=teach":{yomit} "-REAL":a "=1SG.O":{na} "=REL":{ri} 
| "1SG.poss":{no} "=mother":{niro} "-deceased":{ni} 

! 3.82 
| "FOC":{irotaki} 
| "1SG.A":{no} "=inform":{kamaNt} "-APPL.REAS":{aNt} "-REAL":a "=2O":{mi} "=REL":{ri} 

! 3.83 
| "1SG.poss":{no} "=grandpa":{charini} 
| "be.strong":{shintsi} "-ADJ":{ri} 
| "3m.S":i "=be":{na} "-FRUS":{vi} "-EP":t "-REAL":a 

! 3.84 
| "1SG.A":n "=expect":{ooya} "-FRUS":{macheve} "-EP":t "-REAL":a "=3n.m.O":{ro} 
| "3n.m.S":o "=IRR":N "-fall":{pary} "-DIR":{an} "-PRF":{ak} "-IRR":e 

! 3.85 
| "3m.A":i "=attach":{tsirik} "-EP":a "-REV":{ry} "-APPL":{ako} "-ICPL":{it} "-REGR":{ah} "-REAL":i "=1SG.O":{na} "=3n.m.O":{ro} 

! 3.86 
| "3m.A":i "=send":{tyaNk} "-IMP.P":{ai} "-EP":t "-PRF":{ak} "-REAL":i "=1SG.O":{na} 
| "Lima":{irimashi} "-LOC":{ki} 

! 3.87 
| "2A":p "=take":a "-DIR":{an} "-PRF":{ak} "-REAL":i "=1SG.O":{na} "=ADV":{raNki} 

! 3.88 
| "1SG.S":n "=take":a "-PRF":{ak} "-IRR":e 
| "now":{ironyaaka} 

! 3.89 
| "2A":p "=make":{aNt} "-REGR":{ah} "-IRR":e "=1SG.O":{na} "=3n.m.O":{ro} 
| "1SG.poss":{no} "=house":{paNko} 

! 3.90 
| "1SG.S":n "=work":{aNt} "-EP":a "-DUR":{vai} "-EP":t "-PRF":{ak} "-REAL":i 
| "many":{osheki} 

! 3.91 
| "this.m" 
| "NEG.REAL" 
| "3m.A":i "=IRR":N "-be.son.of":{tomiNt} "-IRR":{ia} "=3m.O":{ri} 
| "person":{atziri} 

! 3.92 
| "FOC":{irotaki} 
| "cast.spell":{matzi} "-EP":t "-PRF":{ak} "-REAL":i "=3m.O":{ri} "=REL":{ri} 

! 3.93 
| "1SG.poss":{no} "=daughter":{shiNto} 
| "EXIST":{tzimatsi} 
| "2S":{pi} "=want":{niNt} "-REAL":a "-AUG":{ni} 
| "NEG.EXIST":{tekatsi} 
| "father":{apa} 

! 3.94 
| "EXIST":{ainiro} "=DUB":{ma} 
| "1SG.S":{no} "=be.hungry":{tash} "-PROG":{atz} "-REAL":i 

! 3.95 
| "EXIST":{tzimatsi} 
| "one":{aparoni} 
| "3m.A":y =CAUS":{oi} "-be.happy":{kimoshiri} "-NMZ":{Nk} "-REAL":i "=REL":{ri} 

! 3.96 
| "NEG.EXIST":{tekatsi} 
| "buy":{amanaNt} "-PROG":{atsi} "-STAT" "=REL":{ni} ! REVISED 
| "NEG.EXIST":{tekatsi} 
| "person":{atziri} 

! 3.97 
| "before":{pairani} 
| "3m.S":i "=be":{kaNt} "-REAL":a 
| "tortoise":{konoya} 
| "3m.S":i "=accompany":{tsipat} "-REAL":a "=3m.O":{ri} 
| "3m.poss":i "=namesake":{namesake} 

! 3.98 
| "WH":{tsika} 
| "2S":{pi} "=be":{kaNt} "-REAL":a 
| "be.good":{kameetsa} "-EP":t "-PRF":{ak} "-REAL":i 

! 3.99 
| "1SG.poss":{no} "=daughter":{shiNto} 
| "engineer":{ingeniero} 
| "3n.m.S":o "=be":{na} "-EP":{tz} "-REAL":i 

! 3.100 
| "1SG.poss":{no} "=daughter":{shiNto} 
| "be.good":{kameetsa} "-ADJ.n.m.":{Nto} 
| "3n.m.S":o "=be":{na} "-EP":{tz} "-REAL":i 

! 3.101 
| "1SG.poss":{no} "=son":{tomi} 
| "be.thin":{matsa} "-ADJ.m.":{ri} 
| "3m.S":i "=be":{na} "-EP":{tz} "-REAL":i 

! 3.102 
| "he":{iriro} "-PL":{ite} 
| "NEG.C":{kaari} 
| "1PL.poss":{a} "=fellowman":{shaniNka} 

! 3.103 
| "NEG.C":{kaari} 
| "thin":{matsari} 
| "dog":{otsitzi} 

! 3.104 
| "NEG.C":{kaari} "=DUB":{ma} 
| "its":{ashi} 
| "state":{estado} 

! 3.105 
| "NEG.REAL":{te} 
| "3m.S":i "=be.thin":{matsa} "-EP":t "-IRR":e 
| "dog":{otsitzi} 


! 3.106 
| "EXIST":{tzimatsi} 
| "one":{aparoni} 
| "person":{atziri} 
| "3m.S":i "=be.called":{pai} "-EP":t "-REAL":a 
| "person’s.name":{naviriri} 

! 3.107 
| "EXIST":{tzimatsi} 
| "ancestor":{iNtakaNtarori} 
| "3m.S": "=be.at":{saik} "-before":{it} "-REAL":a 
| "here":{aka} ! IS IT A SPANISH LOAN 
| "3m.S" "=say" "-EP"-REAL=3m.O" 
| "person’s.name" 

! 3.108 
| "WH":{tsika} 
| "be.called":{pai} "-EP":t "-REAL":a 
| "2S":p "=do":{aNt} "-IRR":e "=REL":{ri} 
| "1SG.A":n "=wait":{ooy} "-EP":{ako} "-APPL":{t} "-PROG":{atz} "-REAL":i "=3n.m.O":{ro} 
| "one":{aparoni} 
| "arrive":{arii} "-EP":t "-IRR":{ia} "=1SG.O":{na} "=REL":{ni} 
| "1SG.poss":{no} "=house":{paNko} "-LOC":{ki} 

! 3.109 
| "3m.A":y "=bring":{am} "-PRF":{ak} "-REAL":i "=1SG.O":{na} "=3m.O":{ri} 
| "one":{aparoni} 
| "lamb":{oisha} 
| "who":{niNka} 
| "be.called":{pai} "-EP":t "-REAL""=ADV.P" 
| "person’s.name":{antoko} 

! 3.110 
| "WH":{tsika} 
| "1SG.poss":{no} "=watch":{riro} "-poss":{te} 
| "3m.S":i "=be.at":{saik} "-PROG":{atz} "-REAL":i 
| "top":{henoki} "-DIM":{ni} 
| "table":{mesa} "-LOC":{ki} 

! 3.111 
| "WH":{tsika} "=DUB":{ma} 
| "be.at":{saik} "-STAT":{atsi} "=Q":{ka} 
| "1SG.A":{atsi} "=see":{ny} "-PRF":{ak} "-REAL": "=3n.m.O" 
| "river-LOC=DEM" 

! 3.112 
| "NEG.REAL":{te} 
| "3m.A":y "=take.IRR":{ay}} "-IRR":e "=3n.m.O":{ro} 
| "3n.m.S":o "=CAP.C":{kara} "-EP":{tz} "-REAL":i 
| "3m.A":i "=know":{yot} "-CAUS":{ak} "-EP":a "-FRUS":{vi} "-EP":t "-IMP.P":{ai} "-REAL":t a "=3m.O":{ri} "=ADV":{ra} ! REVISED 

! 3.113 
| "EXIST":{tzimatsi} 
| "3n.m.poss":o "=son":{tomi} 
| "3n.m.S":o "=CAP.C":{kara} "-EP":{tz} "-REAL":i 
| "three":{mava} 

! 3.114 
| "3m.A":n "=corral":{kovari} "-EP":t "-APPL":{ako} "-EP":t "-PRF":{ak} "-REAL":i "=1SG.O":{na} 
| "hospital":{osipitari} "-LOC":{ki} 
| "big.n.m":{aNtaro} "-PL":{paye} 

! 3.115 
| "1SG.S":n "=work":{aNta} "-DUR":{vai} "-EP":t "-PRF":{ak} "-REAL":i 
| "hospital":{osipitari} "-LOC":{ki} 
| "big.n.m":{aNtaro} "-PL":{paye} 

! 3.116 
| "3m.S"i "=be.at":{saik} "-REAL":i 
| "big.n.m":{aNtaro} "-LOC":{ki} 
| "tree":{inchato} 

! 3.117 
| "2S":{pi} "=IRR":N "-cut":{chek} "-IRR":e 
| "big":{aNtaro} "-CL:small.thin.flexible":{shi} 
| "palm.sp.":{koNpiro} "-leaf":{shi} 

! 3.118 
| "3m.S":y "=make":{aNt} "-EP":{tz} "-REAL":i 
| "big"":{aNtaro} -AUG":{ite} 
| "house":{paNkotsi} 

! 3.119 
| "big":{aNtaro} "-AUG":{saNte} 
| "2poss":{pi} "=ear":{yeNpita} 

! 3.120 
| "EXIST":{tzimatsi} 
| "1SG.poss":n "=child":{eentsi} "-poss":{te} 
| "EXIST":{tzimatsi} 
| "small":{iyaani} "-DIM":{ni} 
| "cry.a.lot ":{shiNka} "-ADJ.m.":{ntzi} 

! 3.121 
| "3n.m.A=pay-EP-REAL=3n.m.O" 
| "small-DIM" 

! 3.122 
| "one":{aparoni} 
| "woman":{kooya} 
| "recently":{avakera} 
| "3n.m.S.big":{aNtaro} "-EP":t "-PROG":{atz} "-REAL":i 

! 3.123 
| "NEG.IRR":{airo} 
| "2A"{pi} "=many":{osheki} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} 

! 3.124 
| "1SG.A":{no} "=see":{ny} {atz} "-PROG":i "-REAL":{ro} !REVISED
| "one":{aparoni} 
| "branch":{ochevo} 
| "another":{pashini} 

! 3.125 
| "lake":{inkaari} 
| "big":{antaro} 

! 3.126 
| "3m.S":y "=see":{amin} "-DIR":{ap} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "many":{osheki} "-AUG":{ni} 
| "1PL.poss":a "=fellowman":{shaniNka} 

! 3.127 
| "1SG.A":{no} "=IRR":N "-bathe":{tyooNk} "-APPL.REAS":{aNt} "-PRF":{ak} "-IRR":{ia} "=3m.O":{ri} 
| "1PL.poss":{a} "=fellowman":{sheniNka} 
| "be.sick":{mantsiya} "-ADJ.m":{ri} 

! 3.128 
| "1SG.A":{no} "=put":v "-EP":a "-DIST":{ye} "-EP":{tz} "-REAL":i "=REL":{ri} 
| "herb":{inchashi} 
| "1SG.A":{no} "=IRR":N "-bathe":{kaa} "-EP":t "-APPL.REAS":{aNt} "-IRR":{ia} "=3m.O":{ri} "=REL":{ri} 
| "be.sick":{mantsiya} "-ADJ.m":{ri} 

! 3.129 
| "leaf":{tsipana} 
| "be.green":{natsiya} "-ADJ.n.m":{ro} 

! 3.130 
| "she":{iroo} 
| "be.good":{kameetsa} "-ADJ.n.m":{Nto} 
| "FOC":{irotaki} 
| "know":{yotani} "-ADJ.n.m.":{tsiNkaro} 
| "1SG.poss":{no} "=son":{tomi} 
| "FOC":{iritaki} 
| "know":{yotani} "-ADJ.m":{tsiNkari} 

! 3.131 
| "be.red":{kiyoNka} "-ADJ.n.m":{ro} 
| "3n.m.S":o "=be":n "-PROG":{atz} "-REAL":i 
| "dress":{kitsa} "-NOM":{rintsi} "=DEM":{ka} 

! 3.132 
| "3n.m.S":o "=happen":{kaNt} "-REAL":a 
| "treat":{amin} "-APPL.REAS":{aNt} "-REAL":a "=3m.O":{ri} "=REL":{ri} 
| "be.sick":{mantsiya} "-ADJ.m":{ri} "-PL":{paye} 

! 3.133 
| "1SG.A":{no} "=listen":{kim} "-DIR":{av} "-REGR":{ah} "-REAL":i "=3n.m.O":{ro} 
| "mother":{ina} "-deceased":{ni} 
| "grandpa":{ani} "-deceased":{ni} 
| "die":{kam} "-REGR":{ah} "-STAT":{atsi} "-ADJ":{ri} "-deceased":{ni} 

! 3.134 
| "be.heavy.ADJ":{tenari} "-AUG":{ni} 
| "1SG.poss":{no} "=wood":{tsima} 

! 3.135 
| "FOC":{irotaki} 
| "1SG.A":{no} "=steam.bathe":{saa} "-EP":t "-INST":{aNt} "-REAL":a "=3m.O":{ri} 
| "be.sick":{mantsiya} "-ADJ.m":{ri} "-small.part":{patsa} "-DIM":{ini}

! 3.136 
| "DEM.n.m":{iroka} 
| "machine":{maakina} "=DEM":{ka} 
| "big":{aNtaro} "-DEGR":{pero} "-EP":t "-PROG":{atz} "-REAL":i 

! 3.137 
| "DEM.n.m":{iroka} 
| "tree":{inchato} "=DEM":{ka} 
| "but":{iro} 
| "big":{aNtaro} "-DEGR":{pero} "-EP":t "-PROG":{atz} "-REAL":i 

! 3.138 
| "NEG.REAL":{te} 
| "3n.m.A":o "=be.like":{shiy} "-IRR":{ia} "=3n.m.O":{ro} 
| "other":{pashini} "=DEM":{ra} 

! 3.139 
| "DEM.n.m":{iroka} 
| "machine":{maakina} "=DEM":{ka} 
| "PP":{ari} 
| "3n.m.A":o "=be.like":{shiy} "-DIR":{av} "-PRF":{ak} "-EP":a "-PL":{he} "-EP":t "-REAL":a "-PL":{ni} 

! 3.140 
| "hen":{tyaapa} "=DEM":{ka} 
| "NEG.REAL":{te} 
| "3n.m.S":{o} N "=be.heavy":{tena} "-DEGR":{piro} "-EP":t "-IRR":e ! REVISED
| "NEG.REAL":{te} 
| "3n.m.A":o "=be.like":{shiy} "-IRR":{ia} "=3m.O":{ri} 
| "rooster":{varipa} 

! 3.141 
| "father-in-law":{koki} 
| "he.FOC":{irintsi} "=EMPH":{kya} 
| "exist":{tzim} "-APPL":{ako} "-EP":t "-STAT":{atsi} 
| "3m.poss":i "=manioc":{kaniri} 

! 3.142 
| "die":{kam} "-PRF":{ak} "-REAL":i 
| "one":{aparoni} 
| "woman":{kooya} 
| "other":{pasini} "-LOC":{ki} "=ADV.P":{raNki} 
| "year":{osarentsi} 

! 3.143 
| "three":{mava} "-EP":t "-once":{apaiNt} "-EP":{tz} "-REAL":i "=REL":{ri} 
| "3m.A":i "=see":{ny} "-PROG":{atz} "-REAL":i "=3m.O":{ri} 
| "vulture":{ameNpori} "-PL":{paye} 

! 3.144 
| "late":{osamani} "-almost":{tya} "-DIR":{an} "-PRF":{ak} "-REAL":i 
| "3m.A":i "=go":{ha} "-EP":t "-APPL.INT":{ashi} "-EP":t "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "3m.poss":{ir} "=brother-in-law":{ani} "-poss":{ri} 
| "3m.poss":i "=house":{paNko} "-CL:small.thin.flexible":{shi} "-LOC":{ki} 

! 3.145 
| "3m.A"i "=say":{kaNt} "-once":{apaiNt} "-EP":{tz} "-REAL":i "=3m.O":{ri} 
| "the.other.day":{chapiNki} 
| "300":{300} 
| "Peruvian.currency":{soles} 

! 3.146 
| "3m.poss":i "=fish":{shima} "-PL":{paye} 
| "some.time.ago":{iNkaraNki} 
| "wrap":{akipa} "-REV":{ry} "-APPL":{ako} "-EP":t "-PRF":{ak} "-REAL":i 

! 3.147 
| "many":{oshiki} 
| "1SG.S":{no} "=be.hungry":{tash} "-REAL":i 
| "be.noon":{taNpatsika} "-ADV":{paite} 

! 3.148 
| "1PL.S":a "=go":{hat} "-IRR":e 
| "be.cold":{katsiNkaite} "-ADJ":{ri} "-LOC":{ki} 

! 3.149 
| "1SG.A":{no} "=see":{ny} "-DIR":{av} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "up":{hinoki} "-EP":t "-DIR":{ap} "-PRF":{ak} "-REAL":i "=ADV.P":{raNki} 
| "sun":{ooryaatsiri} 
| "solar.deity":{pava} 

! 3.150 
| "3m.S":i "=go":{ken} "-APPL.INT":{ashi} "-PL":{he} "-EP":t "-DIR":{an} "-REGR":{ah} "-REAL":a 
| "other":{pashini} 
| "downriver":{kiriNka}
| "other":{pashini} 
| "upriver":{katoNko} 

! 3.151 
| "3m.A":i "=walk":{kin} "-CAUS":{ak} "-DIR":{an} "-PRF":{ak} "-REAL":i "=1SG.O":{na} 
| "inside":{intsoNpoi} "-LOC":{ki} "=ADV":{Nta} 
| "3m.A":i "=walk":{kin} "-CAUS":{ak} "-DIR":{an} "-PRF":{ak} "-REAL":i "=1SG.O":{na} 
| "outside":{iNtakiro} "=ADV":{Nta} 

! 3.152 
| "PP":{ari} "3n.m.S":o "=be.at":{saik} "-DIR":{ap} "-PRF":{ak} "-REAL":i "=REL":{ri} 
| "mission":{misión} 
| "this.side.of.the.river":{iNtatzikiroNta} 

! 3.153 
| "sister":{chooki} 
| "3n.m.S":o "be.at":{saik} i 
| "closeby":{okaakini} 

! 3.154 
| "1SG.poss":{no} "=husband":{imi} "-CL:quantity":{poroki} "=DEM":{ra} 
| "there.he.is":{hiri} 
| "3m.S":i "=be.at":{saik} "-EP":a "-CL:quantity":{poroki} "-EP":{tz} "-REAL":i "=ADV":{ra} 

! 3.155 
| "here.it.is":{hiroka} 
| "2poss":{pi} "=house":{paNko} "=DEM":{ka} 

! 3.156 
| "1SG.poss":{no} "=wife":{ina} 
| "here.it.is":{hirika} 
| "3m.poss":i "=meat":{vatsa} 
| "deer":{maniro} 
| "2S":{pi} "=IRR":N "-cook":{kotsi} "-EP":t "-DIR":{av} "-PRF":{ak} "-IRR":e 

! 3.157 
| "not.yet":{tekira} 
| "3n.m.S":o "=IRR":N "-cook":{posa} "-EP":t "-IRR":e 
| "2poss":{pi} "=manioc":{kaniri} 

! 3.158 
| "still":{aikiro} 
| "3n.m.S":o "=leave":{shitov} "-PROG":{atz} "-REAL":i 
| "water":{nihaa} 

! 3.159 
| "a.lot":{osheki} 
| "1SG.S":{no} "=want":{niNt} "-EP":{tz} "-REAL":i 
| "1SG.S":{no} "=play":{nyaatsa} "-EP":t "-IRR":{ia} 

! 3.160 
| "SG.S":n "=arrive":{aree} "-EP":t "-APPL.REAS":{aNt} "-REGR":{ah} "-REAL":a "=REL":{ri} 
| "be.strong":{shintsi} "-ADV":{ni} 

! 3.161 
| "PP":{ari} "=EMPH":{kya} "=ADV":{ro} 
| "1SG.A":{no} "=make.a.hunting.blind":{miNka} "-EP":t "-PRF":{ak} "-REAL":a "=3n.m.O":{ro} 
| "1SG.A":{no} "=fell":{tov} "-APPL.REAS":{aNt} "-REAL":a "=3n.m.O":{ro} "=REL":{ri} 

! 3.162 
| "PP":{ari} "=DUB":{taima} 
| "tomorrow":{osaikera} 
| "small":{kapichi} "-be.morning":{kitaite} 
| "1SG.S":n "=go.up":{atai} "-EP":t "-IRR":e 

! 3.163 
| "PP":{ari} "=DUB":{ma} 
| "drink":{ir} "-PRF":{ak} "-IRR":e "=3n.m.O":{ro} 
| "blood":{iraa} "-ABS":{ntsi} 

! 3.164 
| "now":{ironya} "=EMPH":{kya} 
| "3m.A":i "=kill":v "-IMP.P":{ai} "-EP":t "-PRF":{ak} "-REAL":i "=3m.O":{ri} 

! 3.165 
| "little":{kapicheeni} 
| "now":{ironyaka} "=EMPH":{ha} 
| "crawl":{kamatsa} "-DUR":{vai} "-EP":t "-REGR":{ah} "-REAL":i "=1SG.O":{na} 
| "outside":{iNtakiro} 

! 3.166 
| "3m.A":y "=throw.away":{ook} "-IMP.P":{ai} "-EP":t "-PRF":{ak} "-REAL":i "=1SG.O":{na} 
| "far.away":{iNtaina} "=EXCL":{ve} 

! 3.167 
| "1PL.EXCL":{naakaite} 
| "1SG.S":{no} "=be.at":{saik} "-EP":a "-PL":{he} "-EP":{tz} "-REAL":i 
| "here":{aka} 

! 3.168 
| "3PL.n.m.":{irooite} 
| "swim":{ama} "-PL":{he} "-EP":t "-PROG":{atz} "-REAL":i 
| "river":{nihaa} "-LOC":{ki} 

! 3.169 
| "he":{iriro} 
| "3m.A":i "=cook":{kotsi} "-BEN":{viNt} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} 
| "3m.A":i "=join":{tsipat} "-REAL":a "=3m.O":{ri} 
| "name":{Pito} 
| "now":{ironyaaka} 

! 3.170 
| "she":{iroo} 
| "2A":{pi} "=say":{kaNt} "-IRR":e 
| "3n.m.A":o "=write":{saNkina} "-EP":t "-IRR":e "=2O":{mi} "=OPT":{ta} 

! 3.171 
| "EXIST":{tekatsi} 
| "1SG.S":n "=take":{ay} "-IRR":e 
| "I.FOC":{naari} 
| "another":{pashini} 

! 3.172 
| "3m.S":i "=say":{kaNt} "-EP":{tz} "-REAL":i 
| "he.FOC":{irirori} 
| "NEG.REAL":{te} 
| "1SG.A":{no} "=know":{yo} "-EP":t "-IRR":e "=3n.m.O":{ro} 

! 3.173 
| "bring":{am} "-PRF":{ak} "-REAL":i 
| "she.FOC":{iroori} 
| "EXIST":{tzimatsi} 
| "3m.A":i "=make":{vetsik} "-APPL":{ako} "-EP":t "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 

! 3.174 
| "only":{intaani} 
| "1SG.poss":{no} "=grandma":{sari} "-DIM":{aniki} "-small.part":{patsa} "-DIM":{ini} 
| "FOC":{iritaki} 
| "I.FOC":{naari} 
| "be.joyous":{kimoshiri} "-EP":t "-CAUS":{ak} "-REAL":a "=1SG.O":{na} "=REL"{ri} 

! 3.175 
| "FOC":{naakataki} 
| "take":a "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 

! 3.176 
| "FOC":{iritaki} 
| "be.at":{saik} "-STAT":{atsi} 
| "one":{aparoni} 

! 3.177 
| "FOC":{irotaki} 
| "1SG.S":o "=IRR":N "-get.dark":{tsiteni} "-EP":t "-DIR":{an} "-PRF":{ak} "-IRR":e 
| "get.worse":{mapero} "-EP":t "-DIR":{an} "-REAL":{ak} i "=1SG.O":{na} ! REVISED

! 3.178 
| "FOC":{irotaki} 
| "3m.A":y "=take":a "-DIR":{ap} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "father":{apa} 
| "3n.m.S":o "=be.at":{saik} "-EP":a "-AUG":{pero} "-EP":t "-APPL.REAS":{aNt} "-DIR":{ap} "-PRF":{ak} "-REAL":a "=REL":{ri} 
| "name.of.village":{Marankiaro} "-LOC":{ki} 

! 3.179 
| "yes":{he} 
| "FOC":{irotaki} 
| "only":{iNtaani} 
| "3m.A":i "=hack.with.a.machete":{pes} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "top":{toNkari} "-LOC":{ki} 
| "rock":{iNpereta} "-LOC":{ki} 

! 3.180 
| "Matsigenka":{MachiyeNka} 
| "3m.S":i "=be":{na} "-ep":{tz} "-REAL":i 
| "FOC":{irotaki} 
| "3m.S":i "=beard":{shipatona} t "-APPL.REAS":{aNt} "-REAL":a "=REL":{ri} 

! 3.181 
| "FOC":{irotaki} 
| "also":{aisatzi} 
| "1PL.S":a "=be.angry":{kis} "-RCP":{av} "-PRF":{ak} "-APPL.REAS":{aNt} "-HAB":{apiNt} "-REAL":a "=REL":{ri} 

! 3.182 
| "FOC":{irotaki} 
| "cotton":{aNpeshi} 
| "1SG.S":n "=drink":{ir} "-PRF":{ak} "-REAL":i 
| "FOC":{irotaki} 
| "1SG.S":n "=drink":{ir} "-REAL":i "=REL":{ri} 
| "3m.A":i "=give":p "-IMP.P":{ai} "-EP":t "-REAL":{ak} "=1SG.O":i {na} "=REL":{ri} REVISED

! 3.183 
| "1SG.A"n "=get":a "-IRR":{ye} "=3m.O":{ri} 
| "1SG.A":n "=get":a "-INST":{aNt} "-REAL":a "=3m.O":{ri} 
| "little":{kapichiini} 
| "money":{kiriiki} 
| "DEM":{iroka} 
| "FOC":{irotaki} 
| "1SG.poss":{no} "=bathe":{tyooNk} "-EP":a "-NMZ":{ntsi} 

! 3.184 
| "3m.S":i "=say":{kaNt} "-EP":{tz} "-REAL":i 
| "1PL.poss":a "=grandfather":{charine} "-poss":{te} 
| "3m.S":i "=tell":{kiNkitsa} "-EP":t "-APPL":{ako} "-EP":{tz} "-REAL":i "=REL":{ri} 
| "one":{aparoni} 
| "1PL.poss":a "=fellowman":{shaniNka} 
| "be":{kaNt} "-STAT":{atsi} "=REL":{ri} 
| "FOC":{iritaki} 
| "hunt":{kovintsa} "-NMZ":{ri} 

! 3.185 
| "1SG.S":{no} "=go":{ha} "-EP":t "-PROG":{aty} "-IRR":e 
| "Lima":{Irimashi} "-LOC":{ki} 
| "PP":{ari} 
| "1SG.S":{no} "=want":{niNta} "-FRUS":{vi} "-EP":t "-REAL":a 
| "1SG.S":{no} "=go":{ha} "-EP":t "-IRR":e "=CNT.F":{mi} 
| "I.C.F":{naintsi} "=DUB":{ma} 
| "NEG.REAL":{te} 
| "1SG.S":{no} "=want":{niNt} "-IRR":e 

! 3.186 
| "you":{aviroka} 
| "EXIST":{tzimatsi} 
| "2poss":{pi} "=coffee":{kahai} "-poss":{te} 
| "2poss":{pi} "=plot":{vani} "-LOC":{ki} 
| "you":{aviroka} "=EMPH":{ha} 
| "EXIST":{tzimatsi} "=DUB":{ma} 
| "you.C.F":{avintsi} 
| "woods":{aNtami} "-EP":t "-PRF":{ak} "-REAL":i 
| "2poss":{pi} "=plot":{vani} 

! 3.187 
| "you":{aviroka} 
| "two":{apite} "-NMZ":{ro} "-PL":{ite} 
| "work":{aNt} "-STAT":{atsi} "=REL":{ni} 
| "plot.of.land":{ovantsi} 

! 3.188 
| "woman":{kooya} "-PL":{paye} 
| "she":{iroo} 
| "cook":{kotsi} "-DUR":{vai} "-EP":t "-STAT":{atsi} "=REL":{ni} 

! 3.189 
| "take":a "-DIR":{an} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "she":{iroori} 
| "be.called":{pait} "-STAT":{ach} "-REAL":a "=REL":{ri} 
| "Irina":{Irina} 

! 3.190 
| "who":{niNka} 
| "have":{ashi} "-EP":t "-REAL":a "=3n.m.O":{ro} "=REL":{ri} 
| "machine":{maakina} "=Q":{ka} 
| "hers":{ashi} 
| "woman":{kooya} "=DEM":{ka} 

! 3.191 
| "1SG.S":{no} "=get":a "-APPL.REAS":{aNt} "-IRR":{ia} "=REL":{ri} 
| "1SG.poss":{no} "=cushma":{mantsaki} 
| "1SG.A":{no} "=IRR":N "-dress":{kitsa} "-EP":t "-APPL.REAS":{aNt} "-IRR":{ia} "=3m.O":{ri} "=REL":{ri} 
| "his":{irashi} 
| "1SG.poss":n "=child":{eentsi} "-DIM":{patsaini} 

! 3.192 
| "NEG.REAL":{te} 
| "NEG.C":{kaari} 
| "mine":{nashi} "=EXCL":{ve} 

! 3.193 
| "NEG.REAL":{te} 
| "3SG.m.IRR":{ir} "=be.accustomed":{amit} "-IRR":{ia} 
| "3m.S":i "=be.at":{saik} "-IRR":e 
| "downriver":{kiriNka} 
| "return":{piy} "-REGR":{ah} "-IRR":a 

! 3.194 
| "3n.m.S":o "=IRR":N "-have":{tzim} "-IRR":e 
| "one":{aparoni} 
| "school":{escuela} 
| "3SG.m.IRR":{iri} "=learn":{yo} "-EP":t "-APPL.REAS":{aNt} "-REGR":{ah} "-IRR":{ia} "=REL":{ri} 
| "1SG.poss":{no} "=fellowman":{shaniNka} "-PL":{paye} 

! 3.195 
| "WH":{tsika} 
| 3n.m.S":o "=go":{ha} "-EP":{tz} "-REAL":i "=Q":{ka} 
| "mother":{ina} 
| "come":{pok} "-DIR":{ap} "-REGR":{ah} "-REAL":i "=3n.m.O":Ø 

! 3.196 
| "3m.A":i "=see":{ny} "-DIR":{ap} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "go":{ha} "-EP":t "-PRF":{ak} "-REAL":i "=3m.O":Ø 

! 3.197 
| "3n.m":o "=eat":{va} "-NMZ":{ri} "-poss":{te} 
| "now":{ironyaaka} 
| "solely":{iNtaani} 
| "3m.A":y "=get":{ay} "-IRR":e "=3O":{ni} "=3n.m.O":{ro} 
| "camonilla":{tzina} 

! 3.198 
| "3m.A":i "=beat":{pos} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "3m.A":i "=insert":{mink} "-ICPL":{it} "-PRF":{ak} "-REAL":i "=3O":{ni} "=3m.O":{ri} 
| "bow":{pyaameni} 
| "3m.poss":i "=anus":{tsiyaki} "-LOC":{ki} 

! 3.199 
| "3m.A":i "=give":p "-PRF":{ak} "=1PL.O":{ai} 
| "money":{kiriiki} "=ADV.P":{raNki} 

! 3.200 
| "1SG.S":{no} "=be.at":{saik} "-EP":a "-PL":{he} "-EP":{tz} "-REAL":i "=ADV":{ka} 

! 3.201 
| "here.it.is":{hiro} "=ADV":{Nto} 
| "2poss":{pi} "=house":{paNko} "=DEM":{Nta} 

! 3.202 
| "2A":p "=take":a "-DIR":{an} "-PRF":{ak} "-IRR":e "=3n.m.O":{ro} 
| "DEM.n.m.":{iroka} 
| "water":{nihaa} "=DEM":{ka} 

! 3.203 
| "2S":{pi} "=want":{niNt} "-PROG":{atz} "-REAL":i 
| "DEM.n.m.":{irora} 
| "coca":{koka} 
| "DEM.n.m.":{iroka} 
| "2S":{pi} "=want":{niNt} "-EP":{tz} "-REAL":i "=REL":{ri} 

! 3.204 
| "DEM.m":{yoka} 
| "3m.S":i "=want":{kov} "-REAL":i 
| "3m.A":y "=get":{ay} "-IRR":e "=3n.m.O":{ro} 
| "contract":{contrato} 

! 3.205 
| "NEG.EXIST":{tekatsi} 
| "do":{aNt} "-IRR":e 
| "DEM.n.m":{irora} 
| "1PL.S":a "=IRR":N "-buy":{aNt} "-APPL.REAS":{ia} "-IRR" "=REL":{ri} ! REVISED

! 3.206 
| "DEM.n.m.":{oka} 
| "now":{ironyaaka} 
| "1SG.A":{no} "=empty":{sai} "-EP"":t "-PROG":{aty} "-IRR":e "=3n.m.O":{ro} 
| "water":{nihaa} 

! 3.207 
| "where":{tsika} 
| "1SG.poss":{no} "=daughter":{shiNto} 
| "NEG.W":{taan} 
| "where":{tsika} "=DUB":{taima} 

! 3.208 
| "where":{tsika} 
| "1SG.poss":{no} "=watch":{riro} "-poss":{te} 
| "there":{ari} 
| "1SG.S":{no} "=put":v "-DIR":{an} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "recently":{iNkaraNki} 
| "maybe":{tema} 
| "here.it.is":{hirika} 

! 3.209 
| "where":{tsika} "=COND":{rika} 
| "1SG.S":n "=take":{ay} "-IRR":e 
| "yarina":{koNpiroshi} 
| "EXIST":{tzimatsi} 
| "1SG.poss":{no} "=land":{vani} "-LOC":{ki} "=DEM":{Nta} 
| "many":{osheki} 
| "yarina":{koNpiroshi} 

! 3.210 
| "what":{tsika} 
| "3n.m.S":o "=be.called":{pai} "-EP":t "-REAL":a "=Q":{ka} 
| "woman":{kooya} "=DEM":{ka} 
| "NEG.REAL":{te} 
| "3n.m.S":o "=IRR":N "-be.good":{kameetsat} "-IRR":e 
| "DEM":{irora} 
| "devil":{kamaaro} 
| "3n.m.S":o "=be":{na} {tz} "-REAL":i ! REVISED

! 3.211 
| "WH":{tsika paita} ! REVISED
| "3m.S":y "=look.for":{amin} "-REAL":i "=REL":{ri} 
| "1SG.poss"{no} "=bag":{tsara} "-poss":{te} "-LOC":{ki} 
| "W.NEG":{taan} "=EMPH":{tya} 

! 3.212 
| "WH":{tsika paita} ! REVISED
| "2S":{pi} "=say":{kaNt} "-PRF":{ak} "-REAL":i "=3m.O":{ri} "=REL":{ri} 
| "3n.m.poss":o "=husband":{imi} "-DIST.REL":{tsori} 
| "1SG.A":{no} "=ask":{sampi} "-EP":t "-APPL":{ako} "-EP":t "-PROG":{atz} "-REAL":i "=3m.O":{ri} 
| "1SG.poss":{no} "=daughter":{shiNto} "-DIST.REL":{tsori} 

! 3.213 
| "WH":{tsika} "=DUB":{ma} 
| "3n.m.S":o "=be.called":{pai} "-EP":t "-REAL":a "=Q":{ka} 
| "2S":{pi} "=want":{niNt} "-EP":{tz} "-REAL":i "=REL":{ri} 

! 3.214 
| "be.called":{pai} "-EP":t "-REAL":a "=EMPH":{kya} 
| "be.called":{pai} "-EP":t "-REAL":a "=Q":{ka} 
| "3m.S":i "=die":{kam} "-APPL.REAS":{aNt} "-PRF":{ak} "-REAL":a "=REL":{ri} 
| "dog":{otsitzi} 
| "NEG.REAL":{te} 
| "NEG.REAL":{te} 
| "yet":{tekira} 
| "3m.S":i "=IRR":N "-die":{kam} "-IRR":e 

! 3.215 
| "WH":{tsika} 
| "3n.m.S":o "=happen":{kaNt} "-REAL":a 
| "2S":{pi} "=speak":{nya} "-DUR":{vai} "-EP":t "-APPL.REAS":{aNt} "-PRF":{ak} "-REAL":a "=REL":{ri} 
| "1SG.S":{no} "=speak":{nya} "-DUR":{vai} "-EP":t "-APPL.REAS":{aNt} "-REAL":a "=REL":{ri} 
| "1PL.poss":a "=word":{nyaa} "-poss":{ni} "-LOC":{ki} 
| "1SG.S":{no} "=go":{ha} "-EP":t "-PRF":{ak} "-REAL":i 
| "school":{escuela} 

! 3.216 
| "WH":{tsika} 
| "2A":{pi} "=do":{kaNt} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} "=COND":{rika} 
| "2poss":{pi} "=arrow":{chakopi} "-poss":{te} "-PL":{paye} 
| "1SG.A":{no} "=pierce.with.arrows":{kiNt} "-APPL.REAS":{aNt} "-REAL":{a} "=3n.m.O":{ro} 
| "bird":{tsimiri} 

! 3.217 
| "WH":{tsika} 
| "3n.m.S":o "=CAP.C":{kara} "-EP":t "-IRR":e 
| "money":{kireeki} 
| "2A":{pi} "=IRR":N "-pay":{pina} "-EP":t "-IRR":e "=1SG.O":{na} "=REL":{ri} 
| "many":{osheki} 

! 3.218 
| "WH":{tsika} 
| "3n.m.S":o "=CAP.C":{kara} "-EP":{tz} "-REAL":i 
| "water":{nihaa} 
| "2S":{pi} "=want":{niNt} "-EP":{tz} "-REAL":i "=REL":{ri} 
| "none":{tekatsi} 

! 3.219 
| "WH":{tsika} 
| "3n.m.S":o "=CAP.C":{kara} "-EP":{tz} "-REAL":i 
| "2S":{pi} "=IRR":N "-come":{pok} "-REGR":{ah} "-IRR":e 
| "afternoon":{sheteni} "=DUB":{taima} 

! 3.220 
| "WH":{tsika} 
| "3n.m.S":o "=CAP.C":{kara} "=IRR":t e "=Q":{ka} ! REVISED 
| "work":{aNt} "-EP":a "-DUR":{vai} "-EP":t "-IRR":e 
| "3m.S":i "=be.morning":{kitai} "-EP":{tz} "-INCH":{ima} "-EP":t "-PRF":{ak} "-IRR":e 

! 3.221 
| "3m.S":i "=be.at":{saik} "-EP":a "-FRUS":{vit} "-PRF":{ak} "-REAL":a 
| "here":{aka} 
| "DEM":{irora} 
| "WH":{tsika} 
| "3m.A":i "=say":{kaNt} "-IMP.P":{ai} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} "=Q":{=ka} 
| "1SG.poss":n "=father":{iri} "-deceased":{ni} "=EXCL":{ve} 

! 3.222 
| "DEM":{irora} 
| "WH":{tsika} 
| "3m.A":i "=say":{kaNt} "-IMP.P":{ai} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} "=ADV":{ra} 
| "rock":{iNpereta} "-EP":{tz} "-REAL":i "=ADV":{ra} 

! 3.223 
| "3n.m.S":o "=look.for":{ny} "-REAL":i 
| "where":{tsika} 
| "3n.m.S":o "=IRR":N "-be.good":{kameetsa} "-EP":t "-IRR":e 
| "3n.m.S":o "=be.at":{saik} "-IRR":e 

! 3.224 
| "2S":{pi} "=go":{ha} "-EP":t "-IRR":e 
| "where":{tsika} 
| "2S":{pi} "=want":{niNt} "-PRF":{ak} "-REAL":a "=3n.m.O":{ro} 

! 3.225 
| "who":{niNka} 
| "woman":{kooya} "=DEM":{Nta} 
| "FOC":{irotaki} 
| "3n.m.poss":o "=fellowman":{sheniNka} 
| "1SG.poss":{no} "=wife":{ina} 
| "FOC":{irotaki} 
| "teach":{yomit} "-APPL.REAS":{aNt} "-STAT":{atsi} "=REL":{ri} 

! 3.226 
| "who":{niNka} "=DUB":{ma} 
| "have":{ashi} "-EP":t "-REAL":a "=3n.m.O":{ro} "=REL":{ri} 
| "DEM":{iroka} 
| "hers":{ashi} "=DUB":{taima} 
| "Irina":{Irina} 

! 3.227 
| "who":{niNka} 
| "come":{pok} "-STAT":{atsi} "-REAL" "=REL":{ri} "=Q":{ka} 
| "3m.S":i "=IRR:N "-come":{pok} "-PROG":{aty} "-IRR":e 
| "stick":{sat} "-APPL.REAS":{aNt} "-ADJ":{tsiNkari} 

! 3.228 
| "who":{niNka} "=DUB":{ma} 
| "3n.m.A":o "=call":{kaim} "-REAL":i "=REL":{ri} 
| "3n.m.A":o "=call":{kaim} "-PROG":{atz} "-REAL":i "=3n.m.O":{ri} 
| "3n.m.poss":o "=brother":{yari} "-poss":{ri} 

! 3.229 
| "when":{arika} 
| "3m.S":i N "=hear":{kim} "-PRF":{ak} "-IRR":{ak-e} ! REVISED
| "who":{niNka} "=COND":{rika} 
| "speak.badly":{kantzima} "-DIM.DEGR":{niNt} "-PRF":{ak} "-REAL":i "=3m.O":{ri} "=REL":{ri} 
| "FOC":{iritaki} 
| "3m.A":i "=IRR":N "-behead":{tsatsiNk} "-IMP.P":{ai} "-PRF":t "-IRR":{ak} e "=3m.O":{ri} ! REVISED 

! 3.230 
| "all":{maaroni} 
| "3m.A":i "=call":{kaNt} "-DIR":{an} "-PRF":{ak} "-REAL":i "=1SG.O":{na} 
| "DEM":{iyoka} 
| "who":{niNka} "=COND":{rika} 
| "where":{tsika} "=COND":{rika} 
| "1SG.S":{no} "=go":{ha} "-EP":t "-IRR":e 

! 3.231 
| "everybody":maaro "<AUG>":{ite} "everybody":{ni} 
| "3m.S":i "=run":{shiy} "-EP":a "-PL":{he} "-EP":t "-DIR":{an} "-PRF":{ak} "-REAL":a 

! 3.232 
| "3m.A":y "=gather":{apoto} "-PL":{he} "-EP":t "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "everybody":{maaroni} 

! 3.233 
| "3m.A":i "=idolize":{pavani} "-EP":t "-REAL":a "=3m.O":{ri} 
| "until":{irosatzi} 
| "3m.S":i "=IRR":N "-come":{pok} "-APPL.REAS":{aNt} "-PRF":{ak} "-IRR":{ia} 
| "somebody":{aparoni} 
| "bring":{am} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} "=REL":{ri} 
| "word":{nyaa} "-ABS":{ntsi} 

! 3.234 
| "PP":{ari} 
| "3n.m.S":o "=happen":{kaNt} "-PROG":{aty} "-REAL":a 
| "3m.poss":i "=fear":{tsaroNka} "-LOC":{ki} "-DIM":{ni} 
| "3m.S":i "=be":{kaNt} "-EP":a "-PL":{he} "-EP":t "-PRF":{ak} "-REAL":i 
| "one":{aparo} "-PL":{paye} 

! 3.235 
| "3m.S":i "=come":{pok} "-APPL.REAS":{aNt} "-PRF":{ak} "-REAL":a "=REL":.{ri} 
| "two":{apite} 
| "pajonalino":{kishii} "-provenance":{satzi} 
| "3m.A":i "=say":{kaNt} "-DIR":{ap} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "one":{aparoni} 
| "1PL.poss":a "=fellowman":{shaniNka} 

! 3.236 
| "3m.S":y "=leave":{ook} "-EP":a "-ICPL":{it} "-REGR":{ah} "-REAL":i 
| "eighteen":{dieciocho} 
| "3n.m.S":o "=be.at":{saik} "-DIR":{an} "-REGR":{ah} "-REAL":i 
| "seven":{siete} 
| "four":{cuatro} 
| "man":{shiraNpari} 
| "three":{mava} 
| "woman":{kooya} 

! 3.237 
| "1SG.S":{no} "=call":{kaim} "-DIR":{an} "-PRF":{ak} "-REAL":i 
| "ouch!":{akaya} "=EXCL":{ve-e-e} ! REVISED 

! 3.238 
| "aha":{ha} 
| "here":{aka} 
| "1SG.poss":n "=DEM":{iroka} 
| "humph":{aa} 
| "NEG.C":{kaari} 
| "wait!":{apaata} "=ADV":{ra} 
| "1SG.poss":{no} "=son":{tomi} 

! 3.239 
| "1SG.A":{no} "=sweep":{pishi} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} 
| "1SG.poss":{no} "=house":{paNko} 
| "1SG.S":{no} "=finish":{tsoNk} "-REAL":a 
| "1SG.A":{no}"=cut.grass":{tsamai} "-EP"":t "-REP":a "-DIST":{ye} "-EP":t "-REGR":{ah} "-REAL":i "=3n.m.O":{ro} 
| "aha":{ha} 
| "this":{iro} 
| "2S":p "=work":{aNta} "-ICPL":{it} "-EP":{tz} "-REAL":i "=REL":{ri} 
| "day":{sheteni} "=ADV.P":{raNki} 

! 3.240 
| "3n.m.A":o "=hit":{pos} "-PRF":{ak} "-REAL":i "=1SG.O":{na} 
| "1SG.poss":{no} "=head":{ito} "-LOC":{ki} 
| "IDEO":{poo-o} 
| "1SG.poss":{no} "=back":{tapi} "-LOC":{ki} 
| "IDEO":{poo-o} 

! 3.241 
| "3n.m.S":o "=escape":{shitov} "-DIR":{an} "-PRF":{ak} "-REAL":i 
| "much":{osheki} 
| "1SG.poss":n "=blood":{ira} "-poss":{ni} 
| "IDEO":{tsikiri} 
| "IDEO":{tsikiri} 

! 3.242 
| "3m.S":i "=hear":{kim} "-DIR":{av} "-PRF":{ak} "-REAL":i "=ADV":{ra} 
| "3m.S":i "=inform":{kamaNt} "-APPL":{ako} "-ICPL":{it} "-EP":{tz} "-REAL":i "=REL":{ri} 
| "jump":{mi} "-EP":t "-DIR":{an} "-PRF"":{ak} "-REAL":a 
| "IDEO":{taNkorek} 

! 3.243 
| "3m.A":i "=pull":{noshik} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "IDEO":{tzinik} 
| "IDEO":{tzinik} 
| "IDEO":{tzinik} 
| "be.close":{okaaki} "-EP":t "-PRF":{ak} "-REAL":i 
| "turtle":{konoya} 

! 3.244 
| "1SG.A":n "=follow":{oya} "-EP":t "-DIR":{an} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "2poss":{pi} "=sister":{reNto} 
| "PP":{ari} "=EXCL":{ve} 
| "be.good":{kameetsa} "-EP":t "-PRF":{ak} "-REAL":i 

! 3.245 
| "WH":{tsika} 
| "1SG.poss":{no} "=daughter":{shiNto} 
| "W.NEG":{taan} "=N.C.FOC":{tya} 
| "WH":{tsika} "=DUB":{taima} 

! 3.247 
| "1SG.A":n "=begin":{iNt} "-DIR":{av} "-PRF":{ak} "-IRR":{ia} "=3m.O":{ri} "=OPT":{ta} 
| "hawk.sp.":{oovero} 
| "well":{intsitya} 
| "hawk.sp.":{oovero} 

! 3.248 
| "come.on":{tsame} 
| "1PL.S":a "=go":{ha} "-EP":t "-IRR":e 
| "1SG.poss":{no} "=house":{paNko} "-LOC":{ki} 

! **************************************************
! Chapter 4 
! Clause linking 
! **************************************************

! 4.1 
| "3m.S":{i} "=go":{hatz} "-REAL":i 
| "river":{pareni} "-LOC":{ki} 
| "3m.S":y "=take":a "-DIR":{an} "-PRF":{ak} "-REAL":i 
| "torch":{saNpi} 
| "3m.A":y "=light":{oot} "-REP":a "-EP":t "-INST":{aNt} "-IRR":{ia} "=3m.O":{ri} "=REL":{ri} 
| "water":{nihaa} "-LOC":{ki} 
| "3m.A":y "=see":{amen} "-IRR":e 
| "fish.sp.":{shima} 

! 4.2 
| "NEG.IRR":{airo} "=COND":{rika} 
| "now":{ironyaaka} 
| "1SG.S":{no} "=bathe.in.hot.water":{saa} "-EP":t "-CUST":{aNt} "-DUR":a "-EP":{vai} "-REAL":{tz-i} ! REVISED
| "NEG.EXIST":{tekatsi} 
| "1SG.A":n "=get.IRR":{ay} "-IRR":e "=REL":{ri} 
| "1SG.S":{no} "=eat.IRR":{ya} "=REL":{ri} 

! 4.3 
| "EXIST":{tzimatsi} 
| "here":{aka} 
| "one":{aparoni} 
| "whachamacallit":{irora} 
| "disobey":{piyatsa} "-EP":t "-PRF":{ak} "-REAL":a "=2O":{mi} "=REL":{ri} 

! 4.4 
| "3n.m.S":o "=CAUS":v "-go":{anii} "-EP":t "-DIR":{av} "-REGR":{ah} "-REAL":i "=3m.O":{ri} 
| "meat":{vatsatsi} 
| "3m.S":y "=bring":{am} "-REGR":{ah} "-REAL":i "=REL":{ri} 
| "3n.m.poss":o "=husband":{ime} 

! 4.5 
| "1SG.A":{no} "=put":{miNk} "-INCH":{imai} "-EP":t "-IRR":{ia} "=3n.m.O":{ro} 
| "stick":{inchakii} 
| "two":{apite} 
| "3n.m.S":o "=be":{kaNt} "-REAL":a 
| "DEM":{oka} 
| "be.at":{saik} "-STAT":{atsi} "=REL":{ni} 
| "here":{aka} 
| "DEM":{oka} 
| "be.at":{saik} "-STAT":{atsi} "=REL":{ni} 
| "there":{aNta} 

! 4.6 
| "who":{niNka} 
| "eat":{ov} "-CAUS":{ak} "-REGR":{ah} "=1PL.O":{ai} "=REL:{ni} "=Q":{ka} 
| "I":{naaka} 
| "I":{naaka} 
| "eat":{ov} "-CAUS":{aka} "-IRR":{ia} "=2O":{mi} "=REL":{ni} 

! 4.7 
| "second.father":{koNpatsiri} "=DEM":{Nta} "=EMPH":{ha} 
| "FOC":{iritaki} 
| "paint":{potsot} "-IRR":e "=3n.m.O":{ro} "=REL":{ni} 
| "now":{ironyaaka} 
| "3n.m.poss":o "=face":{poro} "-LOC":{ki} 

! 4.8 
| "EXIST":{tzimatsi} 
| "3n.m.poss":o "=branch":{chevo} 
| "hang":{airik} "-STAT":{acha} "=REL":{ri} 
| "top":{henoki} "=DEM":{Nta} 

! 4.9 
| "2S":p "=look.for":{amin} "-IRR":e 
| "stone":{mapi} 
| "be":{kaNt} "-EP":a "-flat":{miroNt} "-EP":a "-CL:small.round":{ki} "-EP":t "-STAT":{acha} "=REL":{ri} 

! 4.10 
| "EXIST":{tzimatsi} 
| "3m.poss":i "=soldier":{soraro} "-poss":{te} "-PL":{paye} 
| "stand":{katziy} "-EP":a "-BEN":{viNt} "-REAL":a "=3m.O":{ri} "=REL":{ri} 
| "see":{amin} "-STAT":{atsi} "=REL":{ri} 

! 4.11 
| "now":{ironyaaka} 
| "day":{sheteni} "=DEM":{ka} 
| "1SG.A":{no} "=IRR":N "-tell":{kiNkitsa} "-EP":t "-APPL":{ako} "-EP":t "-IRR":e "=3m.O":{ri} 
| "one":{aparoni} 
| "1PL.poss":a "=fellowman":{shaniNka} 
| "3m.A":i "=call":{kaNt} "-IMP.P":{ai} "-EP":{tz} "-REAL":i "=3m.O":{ri} 
| "person’s.name":{ApiiNka} 
| "be.at":{saik} "-STAT.T":{aintsi} "=REL":{ri} "=ADV":{ka} 
| "here":{aka} 
| "1PL.poss":a "=village":{naNpi} "-LOC":{ki} "=DEM":{ka} 

! 4.12 
| "he":{iriro} "-PL":{ite} 
| "work":{aNtavai} "-STAT":t "=REL":{atsi=ri} ! REVISED 
| "1SG.poss":{no} "=land":{vani} "-LOC":{ki} 
| "1SG.A":{no} "=IRR":N "-pay":{pinat} "-EP":a "-PL":{he} "-EP":t "-PROG":{aty} "-IRR":e "=3m.O":{ri} 

! 4.13 
| "you":{aviroka} 
| "go":{ha} "-EP":t "-STAT":{atsi} "=REL":{ni}
| "forest:{aNtami} "-LOC":{ki} 
| "2S":p "=look.for":{amin} "-IRR":e 
| "meat":{vatsatsi} 
| "1PL.A":a "=eat":v "-IRR":{ia} "=3m.O":{ri} 

! 4.14 
| "when":{arika} 
| "3m.S":i "=IRR":N "-hear":{kim} "-PRF":{ak} "-IRR":e 
| "who":{niNka} "=COND":{rika} 
| "speak.badly":{kantzima} "-DIM":{niNt} "-PRF":{ak} "-REAL":i "=3m.O":{ri} "=REL":{ri} 
| "FOC":{irotaki} 
| "3m.A":i "=IRR":N "-behead":{tsatsiNk} "-IMP.P":{ai} "-EP":t "-PRF":{ak} "-IRR":e "=3m.O":{ri} 

! 4.15 
| "much":{osheki} 
| "3n.m.S":o "=weigh":{tena} "-EP":{tz} "-REAL":i 
| "DEM":{oka} 
| "be":{kaNt} "-EP":a "-DUR":{vai} "-EP":t "-DIST":a "-EP":{ye} "-STAT":t "=REL":{acha=ri} ! REVISED

! 4.16 
| "nevertheless":{kantzimaiNtacha} 
| "be.at":{saik} "-STAT":{atsi} 
| "two":{apite} "-NMZ":{ro} "-PL":{ite} 
| "3m.A":i "=put":{miNki} "-PRF":t "-REAL":{ak} "=1SG.O":i "=REL":{na=ri}  ! REVISED
| "1SG.poss":n "=steel":{ashiro} "-poss":{te} 

! 4.17 
| "3m.A":y "=bring":{am} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "blessing":{tasoriNka} "-NMZ":{ntsi} 
| "3m.A":y "=bring":{am} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "CAUS":{ov} "-pass":{avis} "-APPL":{ako} "-EP":t "-REGR":{ah} "=1PL.O":{ai} "=REL":{ni} 

! 4.18 
| "1Pl.A":a "=make.holes":{mok} "-PRF":{ak} "-IRR":e "=3n.m.O":{ro} 
| "much":{osheki} 
| "3n.m.S":o "=be.hard":{kiso} "-CL:small.round":{ki} "-EP":{tz} "-REAL":i 
| "be.red":{kityoNka} "-CL:small.round":{ki} "-EP":t "-STAT":{atsi} "=REL":{ri} 

! 4.19 
| "womanizer":{mayeNpiri} 
| "3m.S":i "=be":{na} "-REAL":{tz-i} ! REVISED
| "3m.A":i "=do":{kaNt} "-IRR":e "=3n.m.O":{ro} 
| "woman":{kooya} 
| "DEM":{irora} "=EXCL":{ve} 
| "3m.A":i "=IRR":N "-open.legs":{tary} "-EP":a "-DUR":{vai} "-EP":t "-IRR":e "=3n.m.O":{ro} 
| "3m.A":y "=smell":{asaNk} "-APPL.REAS":{aNta} "-DUR":{vai} "-IRR":t "=3n.m.O":{e=ro} ! REVISED
| "WH":{tsika paita} 
| "3m.S":i "=want":{niNt} "-PRF":{ak} "-REAL":a "=REL":{ri} 
| "he":{irirori} 

! 4.20 
| "PP":{ari} 
| "3n.m.S":o "=CAP.C":{kara} "-EP":{tz} "-REAL":i 
| "3m.A":i "=tell":{keNkitsa} "-EP":t "-PRF":{ak} "-REGR":a "-REAL":i "=1SG.O":{na} "=REL":{ri} 
| "grandpa":{aani} "-deceased":{ni} 

! 4.21 
| "NEG":{te} "=EMPH":{ha} 
| "1SG.A":{no} "=ask":{saNpi} "-EP":t "-IRR":e "=2O":{mi} 
| "WH":{tsika} 
| "3n.m.S":o "=CAP.C":{kara} "-EP":{tz} "-REAL":i 
| "2A":{pi} "=want":{kov} "-APPL":{ako} "-EP":t "-IRR":e "=1SG.O":{na} "=REL":{ri} 

! 4.22 
| "3n.m.S":o "=see":{ny} "-REAL":i 
| "WH":{tsika} 
| "3n.m.S":o "=be.good":{kameetsa} "-EP":{tz} "-REAL":i 
| "3n.m.S":o "=be.at":{saik} "-IRR":e 

! 4.23 
| "now":{ironyaaka} 
| "pass":{avis} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "meanwhile":{oponya} 
| "look.for":{amin} "-REAL":i 
| "WH":{tsika} "=COND":{rika} 
| "3n.m.S":o "=be.at":{saik} "-IRR":e 
| "there":{aNta} 

! 4.24 
| "3m.A":y "=make":{aNt} "-APPL.INT":{ashi} "-EP":t "-PRF":{ak} "-REAL:i "=1SG.O":{na} 
| "corral":{taNtotsi} 
| "WH":{tsika} 
| "1SG.S":{no} "=be.at":{saik} "-REAL":i 

! 4.25 
| "NEG.EXIST":{tekatsi} 
| "annoy":{nyashiriNk} "-DIR":{ap} "-REGR":{ah} "=1PL.O":{ai} "=REL":{ni} 

! 4.26 
| "EXIST":{tzimatsi} 
| "1SG.A":n "=bring":{am} "-PRF":{ak} "-REAL":i "=REL":{ri} 
| "recently":{iNkaraNki} 
| "here":{aka} 

! 4.27 
| "die":{kam} "-PRF":{ak} "-REAL":i 
| "3m.poss":i "=bow":{pyaameni} 
| "3m.poss":i "=anus":{tsiyaki} "-LOC":{ki} 
| "3m.A":i "=stick":{sat} "-EP":{ai} "-IMP.P":t "-DIR":{an} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 

! 4.28 
| "EXIST":{tzimatsi} 
| "here":{aka} 
| "one":{aparoni} 
| "whachamacallit":{irora} 
| "disobey":{piyatsa} "-EP":t "-PRF":{ak} "-REAL":a "=2O":{mi} "=REL":{ri} 
| "3m.A":y "=bring":{am} "-EP":{ai} "-IMP.P":t "-PRF":{ak} "-REAL":i "=3m.O":{ri} 

! 4.29 
| "then":{ponya} 
| "3n.m.A.follow":{oya} "-EP":t "-DIR":{an} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "DEM":{iroka} "=EXCL":{ve} 
| "river":{nihaa} "=DEM":{ka} 
| "3m.A":i "=say":{kaNt} "-IMP.P":{ai} "-REAL":{tz} "=3n.m.O":{i=ro} ! REVISED
| "river’s.name":{Paukartambo} 

! 4.30 
| "3n.m.S":o "=say":{kaNta} "-FRUS":{ve} "-EP":t "-PRF":{ak} "-REAL":a "=3n.m.O":{ri} 
| "recently":{iNkaraNki} 
| "see":{amen} "-DIR":{ap} "-PROG":{atz} "-REAL":i "=3n.m.O":{ro} 
| "her":{ashi} 
| "she":{iroori} 
| "be.wrinkled":{aNpitsa} "-EP":{ye} "-DIST":t "-PRF":{ak} "-REAL":a 

! 4.31 
| "3n.m.A":o "=heat":{saava} "-EP":t "-APPL.INT":{ashi} "-EP":t "-REGR":{ah} "-REAL":i "=3n.m.O":{ro} 
| "water":{nihaa} 
| "3n.m.A":o "=peel":{pitziry} "-INST":{aNt} "-REGR":{ah} "-REAL":a "=3n.m.O":{ro} "=REL":{ri} 
| "3n.m.S":o "=grow.hair":{vitzit} "-EP":a "-DIST":{ye} {t} "-PRF":{ak}"-REAL":i ! REVISED
| "hand":{ako} "-LOC":{ki} 

! 4.32 
| "grandseer":{aani} 
| "1SG.S":{no} "=kill":v "-PRF":{ak} "-REAL":i 
| "one":{aparoni} 
| "NEG.REAL":{te} 
| "3m.S":i "=be.similar":{shiy} "-IRR":{ia} "=3m.O":{ri} 
| "other":{pashini} "-PL":{paye} 

! 4.33 
| "1SG.A":{no} "=want":{kokov} "~DIR":{av} "-EP":a "-FRUS":{ve} "-EP":t "-REAL":a "=3m.O":{ri} 
| "DEM":{oka} 
| "much":{osheki} 
| "NEG.REAL":{te} 
| "3n.m.S":o "=IRR":N "-weigh":{tena} "-EP":t "-REAL":e 

! 4.34 
| "you":{aviroka} "-PL":{te} 
| "NEG.REAL":{te} 
| "2A":{pi} "=IRR":N "-pay.attention":{kimisaNta} "-PL":{het} "-IRR":e "=1SG.O":{na} 
| "PP":{ar} 
| "1SG.A":{no} "=IRR":N "-punish":{pasat} "-PRF":{ak} "-IRR":e "=2O":{mi} 

! 4.35 
| "afternoon":{sheteni} "=ADV.T":{raNki} 
| "2poss":{pi} "=sister":{reNto} 
| "take":a "-DIR":{an} "-REGR":{ah} "-REAL":i "=3m.O":{ri} 
| "sheep":{oisha} "-PL":{paye} 
| "3n.m.A":o "=eat":v "-CAUS":{ak} "-REAL":a "=3m.O":{ri} 
| "3m.poss":{ir} "=grass":{inchashi} "-poss":{ri} 

! 4.36 
| "PP":{ari} 
| "3n.m.S":o "=be.similar":{kimi} "-EP":t "-REAL":a 
| "before":{pairani} 
| "also":{aisatzi} 
| "I":{naari} 
| "sister":{chooki} "-deceased":{ni} 
| "ago":{ovakera} 
| "3n.m.S":o "=leave":{shitov} "-DIR":{ap} "-REGR":{ah} "-REAL":i 
| "her.blood":{iraani} 
| "FOC":{irotaki} 
| "1SG.A":{no} "=know":{yo} "-EP":t "-APPL.REAS":{aNt} "-REAL":a "=3n.m.O":{ro} "=REL":{ri} 

! 4.37 
| "3m.A":i "=see":{ny} "-DIR":{av} "-PRF":{ak} "-REAL":e "=3m.O":{ri} 
| "FOC":{irotaki} 
| "3m.S":i "=close.eyes":{machok} "-REAL":a "-AUG":{ni} 
| "die":{kam} "-PRF":{ak} "-REAL":i 
| "3m.A":y "=wrap":{aNponat} "-PRF":{ak} "-REAL":e "=3m.O":{ri} 
| "EXIST":{tzimatsi} "=COND":{rika} 
| "3m.poss":i "=blanket":{pashikaro} 

! 4.38 
| "here":{aka} 
| "1SG.A":{no} "=draw":{saNkina} "-EP":t "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "crocodile":{kosani} ".m":{ri} 

! 4.39 
| "afterwards":{ponyashitaka} 
| "3m.A":i "=put":v "-IMP.P":{ai} "-EP":t "-PRF":{ak} "-REAL":i "=1SG.O":{na} 
| "big":{aNta} ".m":{ri} 
| "needle.m":{kitsapi} ! REVISED
| "here":{aka} 
| "1SG.poss":{no} "=ear":{yeNpita} "-LOC":{ki} 

! 4.40 
| "DEM":{iroka} 
| "mud":{kipatsi} 
| "3n.m.S":o "=be":{na} "-EP":{tz} "-REAL":i 
| "be.black":{kisaa} "-ADJ":{ri} "=DEM":{ka} 
| "clay":{pitsitsari} 

! 4.41 
| "lead":{heva} "-EP":t "-APPL.SOC":{ak} "-APPL.REAS":{aNt} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} "=REL":{ri} 

! 4.42 
| "see":{amen} "-APPL.SOC":{ak} "-APPL.REAS":{aNt} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} "=REL":{ri} 

! 4.43 
| "1SG.S":{no} "=eat":v "-APPL.REAS":{aNt} "-HAB":{apiNt} "-REAL":a "=REL":{ri} 

! 4.44 
| "1PL.S":a "=‪urinate":{tsiNt} "-APPL.REAS":{aNt} "-HAB":{apiNt} "-REAL":a "=REL":{ri} 

! 4.45 
| "EXIST":{tzimatsi} 
| "two":{apite} 
| "3m.S":i "=eat":v "-APPL.REAS":{aNt} "-HAB":{apiNt} "-REAL":a "=REL":{ri} "-PL":{ite} 
| "3m.poss":i "=house":{paNko} "-LOC":{ki} 

! 4.46 
| "lead":{heva} "-REAL":a "=REL":{ri} 
| "woman":{kooya} 
| "NEG.REAL":{te} 
| "3n.m.A":o "=want":{niNt} "-PRF":{ak} "-REGR":a "-IRR":e "=1SG.O":{na} 
| "1SG.A":{no} "=visit":{vitsa} "-EP":t "-IRR":{ia} "=3n.m.O":{ro} 
| "3n.m.poss":o "=be.in.big.quantity":{naNpi} "-LOC":{ki} 

! 4.47 
| "who":{niNka} 
| "die":{kam} "-STAT":{aintsi} "=REL":{ri} 
| "Pichanaki":{Pichanaki} "=DEM":{Nta} 
| "die":{kam} "-PRF":{ak} "-REAL":i 
| "work":{aNt} "-APPL":{ako} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} "=REL":{ri} 

! 4.48 
| "WH":{tsika} 
| "3n.m.":o "=COP.CAP":{kara} "-EP":{tz} "-REAL":i "=Q":{ka} 
| "person":{atziri} 
| "fill":{tet} "-STAT":{acha} "=REL":{ri} 
| "car":{kaaro} "-LOC":{ki} "=DEM":{ra} 
| "few":{pashini} 
| "person":{atziri} 

! 4.49 
| "be.called":{pai} "-EP":t "-REAL":a "=Q":{ka} 
| "3n.m.S":o "=crash":{pos} "-APPL.REAS":{aNt} "-PRF":{ak} "-REAL":a "=REL":{ri} 
| "car":{kaaro} "=DEM":{ra} 
| "work":{aNt} "-APPL":{ako} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} "=REL":{ri} 
| "NEG.REAL":{te} 
| "3m.A":y "=see":{amin} "-EP":a "-AUG":{piro} "-EP":t "-IRR":e "=3n.m.O":{ro} 
| "3m.S":y "=see":{amin} "-EP":a "-DUR":{vai} "-EP":{tz} "-REAL":i 
| "river":{pareni} "-LOC":{ki} 

! 4.50 
| "DEM":{iroka} 
| "pumpkin":{pachaka} 
| "1SG.S":n "=take":a "-APPL.REAS":{aNt} "-REAL":a "=REL":{ri} 
| "water":{nihaa} 
| "recently":{ovakera} "-AUG":{ni} 
| "NEG.EXIST":{tekatsi} 
| "1SG.poss":n "=pot":{oya} "-poss":{te} 
| "FOC":{irotaki} 
| "DEM":{iroka} 
| "1SG.A":{no} "=place":v "-APPL.REAS":{aNt} "-REAL":a "=3n.m.O":{ro} "=REL":{ri} 
| "manioc.beer":{pyarentsi} 

! 4.51 
| "be.necessary":{ontzimatye} 
| "grandfather":{charine} 
| "3m.A":i "=IRR":N "-pepper":{tsikana} "-EP":t "=1PL.O":{ai} 
| "3n.m.S":o "=happen":{kaNt} "-IRR":{ia} "=EMPH":{kya} 
| "3n.m.A":o "=be.in.pain":{katsit} "-APPL.REAS":{aNt} "-REAL":a "=REL":{ri} 
| "1PL.poss":a "=arrow":{chakopi} "-poss":{te} 

! 4.52 
| "3m.A":y "=help":{amitako} "-EP":t "-REP":a "-PL":{he} "-EP":t "-PRF":{ak} "=1PL.O":{ai} 
| "1PL.S.look.for":{amen} "-REAL":i 
| "other":{pashini} 
| "speak":{nyaavai} "-PL":{he} "-EP":t "-STAT":{atsi} "=REL":{ni} 

! 4.53 
| "DEM":{iroka} 
| "1SG.poss":{no} "=fabric":{tya} "-poss":{ni} "-PL":{paye} 
| "DEM":{iroka} 
| "1SG.A":{no} "=weave":{shitzik} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 

! 4.54 
| "day":{sheteni} 
| "1PL":a "=COP.CAP":{kara} "-PL":{he} "-EP":t "-REAL":{aiy} "-PL":{i-ni} ! REVISED
| "all":{maaroni} 
| "1SG.S":{no} "=be.at":{saik} "-PL":a "-EP":{he} "-REAL":{tz} "=ADV":{i=ka} ! REVISED

! 4.55 
| "cry":{ira} "-PRF":{ak} "-REAL":a 
| "3n.m.A":o "=say":{kaNt} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} 
| "2S":p "=cry":{ira} "-PRF":{ak} "-REAL":a "=EMPH":{poo} 
| "PP":{ari} 
| "2S":{pi} "=be":{kaNta} "-ICPL":{it} "-PROG":{aty} "-REAL":a "-AUG":{ni} 
| "2S.cry":{pirapira} "~EP":t "-REAL":a 

! 4.56 
| "much":{osheki} 
| "3m.S":i "=be.afraid":{tsarov} "-EP":a "-AUG":{ni} "-EP":{tz} "-REAL":i 
| "NEG.REAL":{te} 
| "3m.S":i "=know":{yo} "-AUG":{ni} "-EP":t "-IRR":e 
| "3m.S":i "=fight":{mana} "-EP":t "-IRR":{ia} 

! 4.57 
| "PP":{ari} 
| "3m.S":i "=say":{kaNt} "-APPL":{ako} "-EP":t "-REAL":a "=REL":.{ri} 
| "owl":{mamaro} 
| "3m.S":i "=kidnap":{koshi} "-EP":{tz} "-REAL":i 
| "one":{aparoni} 
| "woman":{kooya} "-DIM":{aniki} 
| "when":{irohatzi} 
| "3m.S":y "=person":{atziri} "-FRUS":{ve} "-EP":t "-REAL":a "-AUG":{ni} 

! 4.58 
| "this.m":{irika} 
| "young.man":{evaNkari} "=this":{ka} 
| "3m.S":i "=want":{kov} "-REAL":i 
| "3n.m.A":o "=love":{niNt} "-IRR":e "=3m.O":{ri} 
| "3m.poss":i "=wife":{ina} 

! 4.59 
| "1SG.A":n "=expect":{ooya} "-FRUS":{macheve} "-EP":t "-REAL":a "=3n.m.O":{ro} 
| "3n.m.S":o"=IRR":N "-fall":{pary} "-DIR":{an} "-PRF":{ak} "-IRR":e 

! 4.60 
| "3n.m.S":o "=finish":{tsoNk} "-REAL":a 
| "3n.m.S":o "=grow.hair":{vitzit} "-PRF":{ak} "-REAL":i 
| "3n.m.poss":o "=breast":{nii} "-LOC":{ki} 

! 4.61 
| "PP":{ari} 
| "3m.A":i "=cut":{tova} "-flesh":{vatsa} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} 
| "3m.poss":i "=leg":{pori} 

! 4.62 
| "much":{osheki} 
| "3m.A":i "=like":{neve} "-EP":t "-REAL":a "=3n.m.O":{ro} 
| "3m.S":i "=go":{ha} "-EP":t "-IRR":e 
| "3m.S":i "=catch.fish":{shima} "-EP":t "-IRR":{ia} 
| "river":{pareni} "-LOC":{ki} 

! 4.63 
| "NEG.IRR":{airo} 
| "some.time.later":{osamani} "-EP":{tz} "-REAL":i 
| "3m.A":i "=see":{ny} "-PROG":{aty} "-IRR":e "=3n.m.O":{ro} 
| "3m.S":i "=grow":{shiriNka} "-flesh":{vatsa} "-thigh":{pori} "-EP":t "-DIR":{an} "-REGR":{ah} "-REAL":i 

! 4.64 
| "3n.m.S":o "=imagine":{shiyakaNt} "-EP":{tz} "-REAL"i 
| "3n.m.poss":o "=husband":{ime} 
| "come":{pok} "-REGR":{ah} "-REAL":{i} "=3m.O":Ø 

! 4.65 
| "1SG.S":{no} "=fear":{tsarov} "-PROG":{atz} "-REAL":i 
| "enclose":{ashi} "-EP":t "-STAT":{acha} "=3n.m.O":Ø 
| "road":{avotsi} 

! 4.66 
| "NEG.REAL":{te} 
| "2S":{pi} "=want":{niNt} "-IRR":e 
| "2S":p "=take":{ay} "-IRR":e 
| "2poss":{pi} "=husband":{imi} 

! 4.67 
| "many":{osheki} 
| "3m.A":i "=like":{neve} "-EP":t "-REAL":a "=3n.m.O":{ro} 
| "3m.S":i "=catch.fish":{shima} "-EP":t "-IRR":{ia} 
| "at.night":{tsiteni} 

! 4.68 
| "decide":{pintsa} "-EP":t "-REGR":{ah} "-REAL":a "=1SG.O":{na} 
| "1SG.S":{no} "=go":{ha} "-EP":t "-REGR":{ah} "-IRR":e 

! 4.69 
| "1SG.A":{no} "=forget":{maisaNt} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "1SG.A":{no} "=IRR":N "=call":{kaim} "-IRR":e "=3n.m.O":{ro} 
| "1SG.poss":{no} "=mother":{niro} 

! 4.70 
| "3m.A":i {nyashiriNk} "=PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "DEM":{yora} "=EXCL":{ve} 
| "DEM":{yora} 
| "horsefly":{shiNpoki} "-PL":{paye} 
| "cricket":{tsitsiri} "=ADV.P":{raNki} 
| "NEG.REAL":{te} 
| "3n.m.S":o "=like":{nimot} "-IRR":e "=3n.m.O":{ro} 
| "3n.m.S":o "=be.at":{saik} "-IRR":e 

! 4.71 
| "before":{pairani} 
| "have":{ashi} "-EP":t "-child":{ani} "-EP":t "-STAT":{acha} "=REL":{ri} 
| "much":{osheki} 
| "3m.A":y "=be.accustomed":{amit} "-REAL":a "=3n.m.O":{ro} 
| "3m.S":i "=IRR":N "=beat":{pos} "-child":{ani} "-EP":t "-IRR":{ia} 

! 4.72 
| "1SG.S":{no} "=think":{kiNkishiri} "-PRF":{ak} "-REAL":a 
| "NEG.COP":{kaari} 
| "you":{aviroka} 

! 4.73 
| "2A":{pi} "=lose":{pi} "-APPL":{ako} "-EP":t "-PRF":{ak} "-REAL":a "=3n.m.O":{ro} 
| "NEG.COP":{kaari} 
| "2poss":{pi} "=land":{vani} 

! 4.74 
| "1SG.S":{no} "=see":{ny} "-REGR":{ah} "-APPL.REAS":{aNt} "-REAL":{tz-i} 
| "NEG.REAL":{te} 
| "2S":{pi} "=IRR":N "-come":{pok} "-IRR":e 

! 4.75 
| "1SG.S":{no} "=fear":{tsarov} "-PROG":{atz} "-REAL":i 
| "NEG.REAL":{te} 
| "1SG.A":{no} "=know":{yo} "-EP":t "-IRR":e "-3n.m.O":{ro} 
| "3m.poss":i "=word":{nyaa} "-poss":{ni} 

! 4.76 
| "3n.m.S":o "=want":{kov} "-EP":a "-FRUS":{ve} "-EP":t "-REAL":a "=OPT":{ta} 
| "3n.m.A":o "=run":{shiy} "-EP":a "-APPL.SEP":{pitsa} "-EP":t "-IRR":{ia} "=3m.O":{ri} "=CNT.F":{mi} 

! 4.77 
| "NEG.REAL":{te} 
| "3m.S":i "=want":{niNt} "-IRR":e 
| "1PL.S":a "=gain.weight":{vatsa} "-EP":t "-IRR":e 
| "little":{kapicheeni} 

! 4.78 
| "1SG.S":{no} "=want":{niNt} "-EP":{tz} "-REAL":i 
| "1SG.S":{no} "=IRR":N "-die":{kam} "-IRR":e "=CNT.F":{mi} 

! 4.79 
| "3m.S":i "=want":{kov} "-REAL":i 
| "3m.S":i "=rise":{tzin} "-DIR":{an} "-REGR":{ah} "-IRR":e "=CNT.F":{mi} 
| "other":{pashini} 
| "NEG.REAL":{te} 
| "3m.S":i "=IRR":N "-be.able":{kaNt} "-REGR":{ah} "-IRR":e 

! 4.80 
| "all":{maaro} "<PL>":{ite} "all":{ni} 
| "3m.S":i "=run":{shiy} "-EP":a "-PL":{he} "-EP":t "-DIR":{an} "-PRF":{ak} "-REAL":a 
| "3m.S":y "=see":{amin} "-APPL":{ako} "-EP":t "-REP":a "-PL":{he} "-IRR":{t} "=1SG.O":{e=na} ! REVISED
| "WH":{tsika} 
| "3n.m.S":o "=happen":{kaNt} "-REAL":a 
| "1SG.S":{no} "=escape":{shitov} "-APPL.REAS":{aNt} "-REAL":a "=REL":{ri} 

! 4.81 
| "when":{aririka} 
| "1PL.S":a "=go":{ha} "-EP":t "-IRR":e 
| "1PL.S":a "=fish":{shima} "-EP":t "-IRR":{ia} 
| "river":{nihaa} "-LOC":{ki} 
| "1PL.S":a "=see":{ny} "-DIR":{ap} "-PRF":{ak} "-IRR":{e} "=COND":{rika} 
| "3m.S":i "=run":{shiy} "-DIR":{an} "-PRF":{ak} "-IRR":e 
| "bird.species":{paaNpatzi} 

! 4.82 
| "3m.S":i "=hear":{kim} "-PRF":{ak} "-IRR":e "=3m.O":{ri} 
| "3m.A":i "=speak":{nyaa} "-APPL.BEN":{veNt} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} 
| "annatto":{potsotzi} 
| "3m.poss":i "=grandfather":{charini} 

! 4.83 
| "1SG.S":{no} "=hear":{kim} "-PRF":{ak-i} ! REVISED
| "2S":{pi} "=want":{kov} "-REAL":i 
| "3m.S":i "=have":{tzim} "-IRR":e 
| "2poss":p "=child":{eentsi} "-poss":{te} 

! 4.84 
| "3n.m":o "=come":{pok} "-DIR":{ap} "-REGR":{ah} "-IRR":e 
| "mother":{ina} 
| "3n.m.S":o "=see":{ny} "-DIR":{ap} "-REGR":{ah} "-IRR":e "=1SG.O":{na} 
| "1SG.S":{no} "=be.at":{saik} "-REAL":i 
| "outside":{iNtakiro} 

! 4.85 
| "much":{osheki} 
| "1SG.A":{no} "=like":{nive} "-EP":t "-REAL":a "=3n.m.O":{ro} 
| "1SG.S":{no} "=play":{nyaatsa} "-EP":t "-IRR":{ia} 

! 4.86 
| "NEG.REAL":{te} 
| "3n.m.S":o "=please":{nimot} "-IRR":e "=3m.O":{ri} 
| "when":{arika} 
| "3m.S":i "=IRR":N "-feel.pain":{katsit} "-IRR":e 
| "3m.poss":i "=stomach":{motya} 

! 4.87 
| "1SG.poss":{no} "=fellowman":{shaniNka} "-PL":{paye} 
| "3m.A":y "=be.accustomed":{amit} "-REAL":a "=3n.m.O":{ro} 
| "3m.S":i "=IRR":N "-steal":{koshi} "-EP":t "-IRR":e 
| "chicken":{varipa} 

! 4.88 
| "1SG.S":{no} "=fear":{tsarov} "-PROG":{atz} "-REAL":i 
| "enclose":{ashi} "-EP":t "-STAT":{acha} "=3n.m.O":Ø 
| "road":{avotsi} 

! 4.89 
| "1SG.S":{no} "=be.afraid":{tsarov} "-EP":a "-DIM":{niNt} "-PROG":{atz} "-REAL":i 
| "1SG.S":n "=walk":{anii} "-EP":t "-IRR":e 
| "at.night":{tsiteni} 

! 4.90 
| "3m.S":i "=know":{yo} "-FRUS":{ve} "-EP":t "-PRF":{ak} "-REAL":a 
| "tiger":{manitzi} "=DEM":{ra} 
| "3m.A":y "=deceive":{amatavi} "-EP":t "-IMP.P":{ai} "-EP":t "-PROG":{atz} "-REAL":i "=3m.O":{ri} 

! 4.91 
| "3n.m.S":o "=be":{kaNt} "-REAL":a 
| "1L.A":a "=learn":{yo} "-EP":t "-APPL.REAS":{aNt} "-REGR":{ah} "-REAL":a "=REL":{ri} 
| "little":{kapichiini} 
| "1PL.S":a "=read":{nyaana} "-DUR":{vai} "-EP":{tz} "-REAL":i 

! 4.92 
| "3n.m.S":o "=be":{kaNt} "-REAL":a 
| "I":{naari} 
| "1SG.A":{no} "=learn":{yo} "-EP":t "-APPL.REAS":{aNt} "-PRF":{ak} "-REAL":a "=REL":{ri} 
| "1SG.S":n "=cure":{aaviNt} "-CUST":{aNt} "-DUR":a "-EP":{vai} "-REAL":{tz-i} ! REVISED 

! 4.93 
| "NEG.REAL":{te} 
| "3m.S":i "=know":{yo} "-EP":t "-IRR":e 
| "3m.S":i "=read":{nyaana} "-EP":t "-IRR":e 
| "NEG.REAL":{te} 
| "3m.S":i "=know":{yo} "-EP":t "-IRR":e 
| "3m.S":i "=write":saNkina "-EP":t "-IRR":e 

! 4.94 
| "much":{osheki} 
| "3m.A":i "=like":{neve} "-EP":t "-REAL":a "=3n.mO":{ro} 
| "3m.A":i "=teach":{vamet} "-REGR":a "-IRR":e "=3m.O":{ri} 
| "young.men":{evaNkari} "-PL":{paye} 
| "WH":{tsika} 
! "3n.m.S":o "=IRR":N "-do":{kaNt} "-IRR":{ia} 
| "3m.S":i "=be.warrior":{vayeri} "-EP":t "-IRR":{ia} 

! 4.95 
| "I":{naaka} 
| "1SG.S":{no} "=believe":{shiri} "-EP":t "-APPL":{ako} "-EP":t "-REAL":a "=3n.m.O":{ro} 
| "1SG.S":n "=achieve":{arii} "-EP":t "-IRR":{ia} "=3n.m.O":{ro} 

! 4.96 
| "3n.m.S":{no} "=imagine":{shiyakaNt} "-EP":{tz} "-REAL":i 
| "die":{kam} "-PRF":{ak} "-REAL":i "=2O":{mi} 

! 4.97 
| "1SG.S":{no} "=think":{kiNkishiri} "-APPL.INT":{ashi} "-EP":t "-REAL":a 
| "WH":{tsika} 
| "2SG":{pi} "=go":{ha} "-EP":t "-PRF":{ak} "-REAL":i 

! 4.98 
| "1SG.S":{no} "=see":{ny} "-REGR":{ah} "-APPL.REAS":{aNt} "-EP":{tz} "-REAL":i 
| "you":{aviroka} 
| "2S":{pi} "=be":{na} "-EP":{tz} "-REAL":i 

! 4.99 
| "nevertheless":{kantzimaintacha} 
| "grandpa":{charine} 
| "3m.S":i "=say":{kaNt} "-EP":{tz} "-REAL":i 
| "NEG.IRR":{airo} 
| "1PL.A":a "=put":v "-REAL"i "=3m.O":{ri} 
| "3m.poss":i "=name":{vairo} 
| "monkey":{koshiri} 

! 4.100 
| "3m.S":i "=say":{kaNt} "-EP":{tz} "-REAL":i 
| "WH":{tsika} 
| "3m.S":i "=be.at":{saik} "-REAL":i "=Q":{ka} 
| "3m.S":i "=say":{kaNt} "-EP":{tz} "-REAL":i 
| "there":{hiri} 
| "3m.S":i "=be.at":{saik} "-REAL":i "=ADV":{Nta} 

! 4.101 
| "3n.m.A":o "=plead":{kamet} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "3m.A":i "=IRR":N "-pay":{pinat} "-IRR":e "=3n.m.O":{ro} 
| "much":{osheki} 
| "money":{kireeki} 

! 4.102 
| "3m.A":i "=speak.badly":{kaNtzimaniNt} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "3m.A":y "=beat":{aNt} "-IRR":e "=3m.O":{ri} 
| "3m.poss":i "=fellowman":{sheniNka} 

! 4.103 
| "before":{pairani} 
| "1PL.poss":a "=grandparents":{charini} "-poss":{te} 
| "3m.S":i "=advise":{kamen} "-EP":a "-PL":{he} "-EP":{tz} "-REAL":i 
| "PP":{ari} 
| "3n.m.S":o "=be.morning":{kitait} "-early":{aman} "-EP":a "-ICPL":{it} "-IRR":e 

! 4.104 
| "PP":{ari} 
| "3m.A":i "=say":{kaNt} "-REGR":{ah} "-APPL.REAS":{aNt} "-REAL":a "=1SG.O":{na} 

! 4.105 
| "PP":{ari} 
| "3m.A":i "=cut":{tova} "-flesh":{vatsa} "-EP":{tz} "-REAL":i "=3n.m.O":{ro}
| "3m.poss":i "=leg":{pori} 

! 4.106 
| "1SG.S":{no} "=poke":{kiy} "-APPL":{ako} "-EP":t "-IRR":e "=3m.O":{ri} "=OPT":{ta} 
| "now":{ironyaaka} 
| "bullet.ant":{manii} 

! 4.107 
| "PP":{aritaki} 
| "3m.S":i "=be":{kaNt} "-REAL":a "=REL":{ri}
| "NEG.REAL":{te} 
| "1PL.A":a "=know":{yo} "-EP":t "-REAL":e "=3n.m.O":{ro} 
| "1PL.A":a "=fix":{vetsik} "-DIR":{av} "-REGR":{ah} "-IRR":e "=3m.O":{ri} 

! 4.108 
| "yes":{he} 
| "PP":{aritaki} 
| "3m.A":i "=IRR":N "-give":p "-PRF":{ak} "-IRR":e "=2O":{mi} 

! 4.109 
| "PP":{aritaki} 
| "3m.A":i "=IRR":N "-burn":{ta} "-PRF":{ak} "=1PL.O":{ai} 
| "solar.deity":{pava} 
| "DEM":{irora} 
| "3m.poss":i "=power":{tasoriNka} 
| "3n.m.S":o "=be":{na} "-EP":{tz} "-REAL":i 

! 4.110 
| "NEG.P":{kaari} 
| "2A":p "=bring":{am} "-APPL.REAS":{aNt} "-REAL":a "=REL":{ri} 
| "3m.poss":i "=foot":{itzi} "-PL":{paye} 
| "deer":{maniro} 

! 4.111 
| "NEG.P":{kaari} 
| "be.accustomed":{amit} "-APPL.REAS":{aNt} "-for.a.while":{apaiNt} "-REAL":a 
| "downriver":{kiriNka} 
| "come.back":{piy} "-REGR":{ah} "-REAL":a 

! 4.112 
| "FOC":{irotaki} 
| "NEG.P":{kaari} 
| "3m.S":i "=have":{tzim} "-APPL.REAS":{aNt} "-REAL":a 
| "3m.poss":i "=poney":{iriiki} "-poss":{te} 
| "3m.A":i "=pay":{pinat} "-REGR":{ah} "-IRR":e "=3m.O":{ri} 
| "3m.poss":y "=person":{atziri} "-poss":{te} "-PL":{paye} 

! 4.113 
| "EXIST":{tzimatsi} 
| "young.man":{evaNkari} "-PL":{paye} 
| "NEG.P":{kaari} 
| "pay.attention":{kimisaNt} "-REGR":{ah} "-REAL":i "=3n.m.O":{ro} "=REL":{ri} 

! 4.114 
| "be.enough":{aritapaki} 
| "2S":{pi} "=bathe":{kaa} "-EP":t "-PRF":{ak} "-REAL":a 

! 4.115 
| "be.enough":{aritapaki} 
| "2S":{pi} "=sleep":{ma} "-PRF":{ak} "-REAL":i 
| "come.on":{tsame} 
| "1PL.S":a "=go":{ha} "-REGR":t "-ICPL":a "-IRR":{it-e} ! REVISED
| "mother":{ina} "-LOC":{ki} 

! 4.116 
| "be.enough":{aritapaki} 
| "2A":{pi} "=pull.out":{tsok-i} 
| "1SG.poss":{no} "=manioc":{kaniri} 

! 4.117 
| "before":{pairani} 
| "NEG.REAL":{te} 
| "3n.m.S":o "=IRR":N "-be.good":{kameetsa} "-EP":t "-IRR":e 
| "1PL.S":a "=do":{kaNta} "-EP":{vai} "-DUR":{ashi} "-APPL.INT":t "-EP":{ia} "-IRR" ! REVISED

! 4.118 
| "be.good":{kameetsa} "-EP":t "-PRF":{ak} "-REAL":i 
| "1SG.A":{no} "=do":{kaNt} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} "=ADV":{ka} 

! 4.119 
| "I":{naari} 
| "now":{ironyaaka} 
| "3n.m.S":o "=CAP.C":{kara} "-EP":{tz} "-REAL":i 
| "1SG.S":n "=do":{aNt} "-EP":{tz} "-REAL":i "=REL":{ri} "=Q":{ka} 
| "I":{naari} 
| "be.good":{kameetsa} "-EP":t "-PRF":{ak} "-REAL":i "=REL":{ri} "=Q"{ka} 
| "or":{o} 
| "NEG.REAL":{te} 
| "3n.m.S":o "=IRR":N "-be.good":{kameetsa} "-EP":t "-IRR":e 

! 4.120 
| "PP":{ari} 
| "1PL.S":o "=IRR":N "-be.able":{kaNt} "-PRF":{ak} "-IRR":e 
| "1PL.get":{ay} "-IRR":e "=3n.m.O":{ro} 
| "word":{nyaantsi} 
| "when":{arika} 
| "1PL.S":a "=study":{nyaana} "-EP":t "-IRR":e 

! 4.121 
| "NEG.REAL":{te} 
| "3n.m.S":o "=IRR":N "-be.able":{kaNt} "-IRR":e 
| "I":{naaka} 
| "1SG.A":n "=take.care.of":{amen} "-IRR":e "=3n.m.O":{ro} 

! 4.122 
| "that":{yoNta} 
| "3m.A":i "=be.able":{kaNt} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "finish":{tsoNk} "-REAL":i "=3n.m.O":{ro} 
| "3m.poss":i "=land":{vani} 

! 4.123 
| "child":{eentsi} "-PL":{paye} 
| "3n.m.S":o "=IRR":N "-have":{tzim} "-PROG":{aty} "-IRR":e 
| "3m.A":y "=help":{amitako} "-EP":t "-IRR":e "=3m.O":{ri} 
| "DEM":{irora} 
| "3m.S":i "=IRR":N "-gather":{koya} "-DUR":{vai} "-EP":t "-IRR":e 
| "plant":{incha} "-CL:small.flat":{shi} "-small.part":{patsa} "-DIM":{ini} 

! 4.124 
| "3n.m.S":o "=IRR":N "-have":{tzim} "-PROG":{aty} "-IRR":e 
| "whachamacallit":{irora} 
| "1PL.S":a "=cross.river":{moNty} "-DIR":{an} "-PRF":{ak} "-IRR":e 

! 4.125 
| "3n.m.A=finish-PRF-REAL=3n.m.O" 
| "3n.m.S":o "=cook.manioc":{kasa} "-DUR":{vai} "-EP":t "-DIR":{an} "-REGR":{ah} "-REAL":i 
| "woman":{kooya} "=DEM":{ka} 

! 4.126 
| "PP":{ari} 
| "begin":{iNt} "-DIR":{an} "-PRF":{ak} "-REAL":a 
| "3m.S":i "=appear":{konyaa} "-EP":{tz} "-REAL":i 
| "owl":{mamaro} 

! 4.127 
| "NEG.IRR":{airo} 
| "3n.m.S":o "=old":{kiNkivaro} "-EP":t "-APPL.REAS":{aNt} "-DIR":{an} "-PRF":{ak} "-REAL":a 
| "quickly":{shintsini} 

! 4.128 
| "afterwards":{iNponyashitakya} 
| "1SG.A":{no} "=boil":{moy} "-CAUS":{ak} "-INCH":{imai} "-EP":t "-REAL":a "=3n.m.O":{ro} 

! 4.129 
| "2A":{pi} "=allow":{shini} "-EP":t "-IRR":e "=3n.m.O":{ro} 
| "1SG.S":{no} "=IRR":N "-cut":{chek} "-IRR":e 
| "2poss":{pi} "=firewood":{saiNpiki} "-poss":{te} 

! 4.130 
| "3m.A":i "=prevent":{tsani} "-REAL":a "=3n.m.O":{ro} 
| "build":{aNt} "-IRR":e 
| "house":{paNkotsi} 

! 4.131 
| "come.on":{tsame} 
| "1PL.S":a "=IRR":N "-be.person":{tziri} "-EP":t "-IRR":e 
| "help":{amitako} "-EP":t "-IRR":e "=3m.O":{ri} "=OPT":{ta} 
| "1PL.A":a "=CAUS":v "-pass":{avis} "-APPL":{ako} "-EP":t "-REGR":{ah} "-IRR":e "=3m.O":{ri} 

! 4.132 
| "1SG.A":n "=choose":a "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "machete":{kotsiro} 
| "1SG.S":n "=go.up":{aNtai} "-EP":t "-PRF":{ak} "-REAL":i 
| "tree":{inchato} "-LOC":{ki} "=DEM":{ra} 

! 4.133 
| "3n.m.S":o "=think":{shiyakaNt} "-EP":{tz} "-REAL":i 
| "come":{pok} "-REGR":{ah} "-REAL":i 
| "then":{ironyaaka} 
| "3m.A":y "=go.up":{aNtai} "-EP":t "-APPL.INT":{ashi} "-EP":t "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "top":{henoki} 

! 4.134 
| "1SG.S":n "=pick":a "-PRF":{ak} "-REAL":i 
| "other":{pashini} 
| "then":{ponyashitaka} 
| "also":{aisatzi} 
| "1SG.A":{no} "=cut":{chek} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 

! 4.135 
| "3m.A":y "=CAUS":o "-be.hard":{kiso} "-EP":t "-PRF":{ak} "-IRR":e "=3m.O":{ri} 
| "vine.species":{shivitsa} "-LOC":{ki} 
| "then":{ponyashitaka} 
| "3m.S":y "=take":a "-PRF":{ak} "-REAL":e 
| "mat":{shitashintsi} 
| "also":{aisatzi} 
| "3m.A":y "=wrap":{aNponat} "-PRF":{ak} "-IRR":e "=3m.O":{ri} 

! 4.136 
| "then":{oponya} 
| "1SG.A":{no} "=IRR":N "-weave":{kirik} "-IRR":e "=3n.m.O":{ro} 
| "cotton":{aNpee} 
| "then":{oponya} 
| "I":{naaka} 
| "1SG.A":{no} "=IRR":N "-dye":{tsak} "-PRF":{ak} "-IRR":e "=3n.m.O":{ro} 

! 4.137 
| "when":{arika} 
| "1PL.A":a "=wash":N "-FRUS":{kiva} "-EP":{ve} "-REGR":t "-IRR":{ah} "=3m.O":{ia=ri} ! REVISED
| "NEG.IRR":{ero} 
| "3m.S":i "=fade":{veha} "-AUG":{pero} "-AUG":{ni} "-EP":t "-REAL":a 

! 4.138 
| "when":{arika} 
| "3n.m.S":o "=grow.big":{santsa} "-EP":t "-DIR":{an} "-PRF":{ak} "-IRR":e 
| "1SG.A":n "=roll.up":{aNpinaik} "-INCH":{imai} "-EP":t "-IRR":{ia} "=3n.m.O":{ro} 

! 4.139 
| "2A":{pi} "=greet":{vitsa} "-EP":t "-DIR":{ap} "-PRF":{ak} "-IRR":{ia} "=3n.m.O":{ro} 
| "grandma":{isha} 
| "if":{arika} 
| "2A":{pi} "=see":{ny} "-PRF":{ak} "-IRR":e "=3n.m.O":{ro} 

! 4.140 
| "die":{kam} "-PRF":{ak} "-REAL":i "=ADV":{ra} "=EMPH":{ha} 
| "3m.S":i "=say":{kaNt} "-EP":{tz} "-REAL":i 
| "I":{naaka} 
| "NEG.REAL":{te} 
| "1SG.S":{no} "=die":{kam} "-IRR":e 

! 4.141 
| "3n.m.A":o "=happen":{kaNt} "-CAUS":{ak} "-DIR":{an} "-PRF":{ak} "-REAL":i "=1SG.O":{na} 
| "3m.A":i "=stick":{sat} "-IMP.P":{ai} "-EP":t "-PRF":{ak} "-EAL":i "=1SG.O":{na} "=ADV":{ra} 
| "one":{aparoni} 
| "medicine":{aaviNtarontsi} 

! 4.142 
| "3n.m.S":o "=be.at":{saik} "-EP":a "-PL":{he} "-EP":{tz} "-REAL":i "=ADV":{ra} 
| "3n.m.S":o "=danger":{koveNka} "-EP":{tz} "-REAL":i 
| "many":{osheki} 
| "tiger":{manitzi} 

! 4.143 
| "CONN":{ironyaaka} 
| "big":{antaro} "-AUG":{ite} 
| "tiger":{manitzi} 
| "3m.S":i "=walk":{ken} "-DIR":{ap} "-PRF":{ak} "-REAL":i 
| "3n.m.S":o "=lie.prostrate":{nary} "-PRF":{ak} "-REAL":a "=ADV":{ra} 

! 4.144 
| "when":{ovakera} 
| "pull.out":{tsop} "-STAT":{acha} "=REL":{ni} 
| "tooth":{aiki} 
| "when":{ovakera} 
| "child":{eentsi} "-EP":t "-DIR":{ap} "-PRF":{ak} "-REAL":i 
| "NEG.IRR":{airo} 
| "throw.away":{ooka} "-DUR":{vai} "-APPL.INT":{ashi} "-EP":t "-REAL":a "=3n.m.O":{ro} 

! 4.145 
| "PP":{ari} 
| "3n.m.S":o "=be.similar":{kimi} "-EP":t "-REAL":a 
| "before":{pairani} 
| "also":{aisatzi} 
| "I":{naari} 
| "when":{ovakera} 
| "sister":{chooki} 
| "3n.m.S":o "=leave":{shitov} "-DIR":{ap} "-REGR":{ah} "-REAL":i 
| "blood":{iraani} 

! 4.146 
| "CONN":{ikaNta} 
| "3m.A":i "=get.drunk":{shiNki} "-EP":t "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "now":{ironyaaka} 
| "armadillo":{ashoshi} "=DEM":{ra} 
| "dig":{kiy} "-PRF":{ak} "-REAL":i 
| "she":{iroori} 

! 4.147 
| "CONN":{okaNta} 
| "now":{ironyaaka} 
| "DEM":{yora} 
| "armadillo":{ashoshi} "=DEM":{ra} 
| "3n.m.S":o "=make":{vitsik} "-PRF":{ak} "-REAL":i 
| "3m.A":i "=say":{kaNt} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "his.sister":{iritsiro} 

! 4.148 
| "solely":{iNtaani} 
| "3m.A":y "=get":{ay} "-REAL":i "=3O":{ni} "=3m.O":{ri} 
| "pifayo":{tzina} 
| "CONN":{okaNta} 
| "CONN":{okaNta} 

| "4.149" 
| "3m.S":i "=clean":{shet} "-PRF":{ak} "-REAL":a 
| "3m.S":i "=clean":{shet} "-PRF":{ak} "-REAL":a 
| "CONN":{ikaNta} 
| "CONN":{ikaNta} 
| "die":{kam} "-PRF":{ak} "-REAL":i 

! 4.150 
| "macaque":{makako} 
| "FOC":{irotaki} 
| "1SG.S":{no} "=be.born":{tzim} "-APPL":{ako} "-EP":t "-PRF":{ak} "-REAL":i 
| "long.ago":{pairani} 

! 4.151 
| "3n.m.S":o "=crush":N "-REP":{pas} "-EP":a "-PROG":t "-IRR":{aty} "=3n.m.O":{e=ro} ! REVISED
| "IDEO":{tsiNki} 
| "IDEO":{tsiNki} 
| "IDEO":{tsiNki} 
| "until":{irohatzi} 
| "3n.m.A":o "=IRR":N "-finish":{tsoNk} "-APPL.REAS":{aNt} "-PRF":{ak} "-IRR":{ia} "=3n.m.O":{ro} 

! 4.152 
| "3n.m.A":o "=IRR":N "-do":{kaNt} "-IRR":e "=3n.m.O":{ro} 
| "until":{irohatzi} "=EMPH":{ta} 
| "3n.mS":o "=leave":{shitov} "-APPL.REAS":{aNt} "-REGR":{ah} "-IRR":{ia} 

! 4.153 
| "3n.m.S":o "=COP.CAP":{kara} "-EP":{tz} "-REAL":i 
| "three":{mava} 
| "3m.A":i "=put":v "-IMP.P":{ai} "-EP":t "-PRF":{ak} "-REAL":i "=1SG.O":{na} 
| "blood":{iraantsi} "=EXCL":{ve} 
| "until":{irohatzi} 
| "1SG.S":{no} "=get.well":{shitako} "-EP":t "-APPL.REAS":{aNt} "-REGR":{ah} "-REAL":a 

! 4.154 
| "PP":{ari} 
| "3m.S":i "=be.at":{saik} "-EP":a "-PL":{he} "-EP":{tz} "-REAL":i 
| "3m.S":i "=talk":{keNkitsa} "-DUR":{vai} "-EP":t "-PL":{aiy} "-REAL":i "-PL":{ni} 
| "until":{irohatzi} 
| "arrive":{aree} "-EP":t "-APPL.REAS":{aNt} "-DIR":{ap} "-PRF":{ak} "-REAL":a "=REL":{ri} 
| "3m.poss":i "=dream":{pochoki} "-poss":{ni} 

! 4.155 
| "La Merced-LOC" 
| "3m.A":i "=dress":{kitsa} "-EP":t "-IMP.P":{ai} "-EP":t "-PRF":{ak} "-REAL":i "=1SG.O":{na} 
| "white":{kitamarori} 
| "until":{irohatzi} 
| "1SG.S":{no} "=go":{ha} "-EP":t "-APPL.REAS":{aNt} "-PRF":{ak} "-IRR":{ia} 

! 4.156 
| "PP":{ari} 
| "3m.S":i "=say":{kaNt} "-APPL":{ako} "-EP":t "-REAL":a "=3m.O":{ri} 
| "owl":{mamaro} 
| "3m.S":i "=kidnap":{koshi} "-EP":{tz} "-REAL":i 
| "one":{aparoni} 
| "woman":{kooya} "-DIM":{aniki} 
| "until":{irohatzi} 
| "3m.S":y "=person":{atziri} "-FRUS":{ve} "-EP":t "-REAL":a "-AUG":{ni} 

! 4.157 
| "FOC":{irotaki} 
| "3m.A":i "=advise":{kamaNt} "-EP":a "-PL":{he} "-EP":{tz} "-REAL":i "=3m.O":{ri} 
| "3m.poss":{ir} "=child":{eentsi} "-poss":{te} "-PL":{paye} 
| "until":{irohatzi} "=EMPH":{ta} 
| "now":{ironyaaka} 

! 4.158 
| "now":{ironyaaka} 
| "man":{shiraNpari} "=DEM":{ka} 
| "3m.A":y "=take":a "-DIR":{an} "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "child":{eentsi} 
| "until":{irohatzi} 
| "3n.m":o "=top.branch":{patsishi} "-LOC":{ki} 
| "kapok.tree":{shina} 

! 4.159 
| "not.yet":{tekira} 
| "3m.A":i "=IRR":N "-fill":{tet} "-IRR":e "=3m.O":{ri} "=OPT":{ta} 
| "3m.A":i "=IRR":N "-bathe":{kaa} "-EP":t "-DIR":{av} "-REGR":{ah} "-IRR":e "=3m.O":{ri} "=OPT":{ta} 
| "dead":{kamiNkari} 
| "3m.S":i "=go":{ha} "-EP":t "-REGR":{ah} "-IRR":e "=OPT":{ta} 
| "well":{kametsa} 

! 4.160 
| "1PL.S":a "=get.white.hair":{pait} "-DIR":{an} "-PRF":{ak} "-REAL":i 
| "child":{eentsi} "-EP":t "-PROG":{aty} "=1PL.O":{ai} 
| "not.yet":{tekira} "=OPT":{ta} 
| "elder":{aapi} "-EP":t "-DIR":{an} "-PRF":{ak} "-IRR":e "=OPT":{ta} 

! 4.161 
| "not.yet":{tekira} 
| "2A":p "=arrive":{arii} "-EP":{tz} "-APPL.PRES":{imo} "-EP":t "-IRR":{ia} "=3m.O":{ri} "=OPT":{ta} 
| "PP":{ari} 
| "whachamacallit":{irora} "=EXCL":{ve} 
| "2S":{pi} "=go":{ha} "-EP":t "-PRF":{ak} "-IRR":e 
| "3n.m.S":o "=IRR":N "-have":{tzim} "-PROG":{aty} "-IRR":e 
| "2S":{pi} "=IRR":N "-kneel.down":{tyerov} "-APPL.INT":{ashi} "-EP":t "-DIR":{ap} "-PRF":{ak} "-IRR":{ia} "=3m.O":{ri} 

! 4.162 
| "if":{aririka} 
| "2A":{pi} "=remove.skin":{mish} "-PRF":{ak} "-IRR":e "=1SG.O":{na} 
| "white":{kitamaro} 
| "1SG.poss":{no} "=meat":{vatsa} 

! 4.163 
| "if":{aririka} 
| "1PL.A":a "=measure":{moNkara} "-EP":t "-PRF":{ak} "-IRR":e "=3n.m.O":{ro} 
| "all":{maaroni} 
| "advice":{kamenaantsi} "=DEM":{ka} 
| "if":{aririka} 
| "1PL.A":a "=measure":{moNkara} "-EP":t "-DIR":{ap} "-PRF":{ak} "-IRR":{ia} 
| "1PL.A":a "=pull.out":{tsok} "-APPL.REAS":{aNt} "-IRR":{ia} "=3n.m.O":{ro} "=REL" 
| "PP":{ari} 
| "1PL.A":a "=see":{ny} "-PRF":{ak} "-IRR":e "=3n.m.O":{ro} 
| "many":{osheki} 
| "3poss":o "=mass":{vatsa} 
| "manioc":{kaniri} 

! 4.164 
| "when":{aririka} 
| "2S":{pi} "=have":{tzim} "-CAUS":{ak} "-PRF":{ak} "-IRR":e "=3n.m.O":{ro} 
| "child":{eentsi} 
| "also":{aisatzi} 
| "be.necessary":{oNtzimatye} 
| "2S":{pi} "=IRR":N "-get.up":{tzin} "-REGR":a "-IRR":e 
| "small":{kapichi} "-be.morning":{kitaite} 

! 4.165 
| "2A":p "=hit":{aNt} "-APPL":{ako} "-EP":t "-DIR":{ap} "-PRF":{ak} "-IRR":e "=3m.O":{ri} 
| "when":{aririka} 
| "3m.S":i "=escape":{shitov} "-DIR":{an} "-PRF":{ak} "-IRR":e 
| "tree.sp":{kanai} "-CL:social.insect":{ki} 
| "PP":{ari} 
| "2A":{pi} "=place":v "-DIR":{an} "-PRF":{ak} "-IRR":e "=3m.O":{ri} 
| "3n.m.poss":o "=ground":{poNkitzi} "-LOC":{ki} 
| "tree":{inchato} "=DEM":{ka} 

! 4.166 
| "if":{aririka} 
| "1PL.S":a "=go":{ha} "-EP":t "-IRR":e 
| "1PL.S":a "=fish":{shima} "-EP":t "=IRR":{ia} 
| "river":{nihaa} "-LOC":{ki} 
| "1PL.S":a "=see":{ny} "-DIR":{ap} "-PRF":{ak} "-IRR":e "=COND":{rika} 
| "3m.S":i "=run":{shiy} "-DIR":{an} "-PRF":{ak} "-IRR":e 
| "bird.species":{paaNpatzi} 
| "PP":{ari} 
| "1PL.S":a "=know":{yo} "-EP":t "-IRR":e "=REL":{ri} 
| "EXIST":{tzimatsi} "=ADV":{ra} 
| "fish":{shima} 

! 4.167 
| "EXIST":{tzimatsi} "=COND":{ri} 
| "manioc.beer":{kapyarentsi} 
| "also":{ahatzi} "=EMPH":{ta} 
| "1PL.A":a "=IRR":N "-give":p "-APPL":{ako} "-EP":t "-DIR":{av} "-PRF":{ak} "-IRR":e "=3m.O":{ri} 

! 4.168 
| "if":{arika} 
| "1PL.A":a "=give":p "-DIR":{av} "-PRF":{ak} "-IRR":e "=3m.O":{ri} 
| "FOC":{iritaki} "=COND":{rika} 
| "shaman":{sheripyari} 
| "want":{kov} "-STAT":{atsi} "=REL":{ri} 
| "3m.A":i "=know":{yo} "-EP":t "=1PL.O":{ai} 
| "1PL.S":a "=IRR":N "-be.good":{kameetsa} "-person":{atziri} "-IRR":e "=COND":{rika} 
| "PP":{ari} 
| "3m.A":i "=blow":{tasoNk} "-PRF":{ak} "=1PL.O":{ai} 

! 4.169 
| "but":{iro} 
| "3n.m.S":o "=leave":{shitov} "-REGR":{ah} "-IRR":e "=COND":{rika} 
| "PP":{ari} 
| "3m.A":i "=paint":{potso} "-ICPL":{it} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} "=REL":{ri} 
| "now":{ironyaaka} 
| "3n.m.poss":o "=face":{poro} "-LOC":{ki} 

! 4.170 
| "go":{ha} "-EP":t "-PRF":{ak} "-REAL":e 
| "woods":{aNtami} "-LOC":{ki} 
| "look.for":{amin} "-IRR":e 
| "animal":{piratsi} 
| "3m.A":i "=eat":v "-APPL":{ako} "-EP":t "-IRR":{ia} "=3n.m.O":{ro} "=REL":{ri} 
| "3n.m.S":o "=leave":{shitov} "-REGR":{ah} "-IRR":e "=COND":{rika} 
| "later":{apaata} 

! 4.171 
| "NEG.IRR.COND":{airorika} 
| "2A":{pi} "=see":{ny} "-REAL":i "=1SG.O":{na} 
| "water":{nihaa} "-LOC":{ki} 
| "PP":{ari} 
| "1SG.S":{no} "=be.at":{saik} "-IRR":e "=REL":{ri} 
| "ground":{kipatsi} "-LOC":{ki} 

! 4.172 
| "NEG.IRR.COND":{airorika} 
| "now":{ironyaaka} 
| "1SG.S":{no} "=bathe.in.hot.water":{saa} "-EP":t "-CUST":{aNt} "-DUR":{a} "-REAL":{vai-tz-i} ! REVISED
| "NEG.EXIST":{tekatsi} 
| "1SG.A":n "=get":{ay} "-IRR":e "=REL":{ri} 
| "1SG.S":{no} "=eat.IRR":{ya} "=REL":{ri} 

! 4.173 
| "NEG.COND":{terika} 
| "3m.S":y "=get":{ay} "-IRR":e 
| "yarina":{koNpiroshi} 
| "PP":{ari} 
| "1SG.S":{no} "=return":{piy} "-REGR":{ah} "-IRR":e 

! 4.174 
| "1SG.S":{no} "=buy":{kaNpitaNt} "-APPL.REAS":{aNt} "-IRR":{ia} 
| "meat":{vatsatsi} 
| "or":{terika} 
| "1SG.S":n "=bring":{am} "-REGR":{ah} "-IRR":e 
| "fish":{shima} 

! 4.175 
| "1SG.S":{no} "=go":{ha} "-EP":t "-PROG":{aty} "-IRR":e 
| "La Merced":{Tsiirishi} "-LOC":{ki} 
| "or":{terika} 
| "1SG.S":{no} "=go":N "-DIR":{kin} "-PRF":{an-ak} "-IRR":{e} ! REVISED
| "Tarma":{Taaroma} "-LOC":{ki} 

! 4.176 
| "1SG.S":{no} "=plant":{paNki} "-EP":t "-PROG":{aty} "-IRR":e 
| "plantain.sp.":{shiira} 
| "or":{terika} 
| "plantain.sp.":{katsimaropa} 

! 4.177 
| "1SG.poss":{no} "=wife":{ina} 
| "3n.m.S":o "=go":{ha} "-EP":t "-PROG":{atz} "-REAL":i 
| "hilltop":{toNkari} "-LOC":{ki} 
| "maybe":{terika} 
| "NEG.IRR":{airo} 
| "return":{piy} "-REGR":{ah} "-REAL":a 

! 4.178 
| "3m.S":y "=arrive":{aree} "-EP":t "-REGR":{ah} "-IRR":{ia} "=CNT.F":{mi} 
| "well":{kametsa} 
| "NEG.IRR":{ero} 
| "3m.A":i "=embarrass":{pashiveNt} "-IMP.P":{ai} "-EP":{tz} "-REAL":i "=3m.O":{ri} "=CNT.F":{mi} 
| "now":{ironyaaka} 
| "Beetle":{Tziivito} 

! 4.179 
| "3m.A":y "=abandon":{ook} "-IMP.P":{ai} "-EP":t "-DIR":{an} "-PRF":{ak} "-REAL":i "=3m.O":{ri}
| "he":{irirori} 
| "3m.S":i "=disobey":{piyatsa} "-EP":t "-REAL":a 
| "NEG.IRR":{ero} 
| "3m.S":i "=disobey":{piyatsa} "-EP":t "-REAL":a "=CNT.F":{mi} 
| "NEG.IRR":{ero} 
| "3m.S":y "=abandon":{ook} "-IMP.P":{ai} "-EP":{tz} "-REAL":i "=CNT.F":{mi} 

! 4.180 
| "later":{apaatatziro} 
| "3m.S":i "=be.at":{saik} "-REAL":i 
| "now":{ironyaaka} 
| "3m.A":i "=transform":{pi} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "stone":{mapi} 
| "NEG.IRR":{airo} "=COND":{rika} 
| "now":{ironyaaka} 
| "3m.S":i "=finish":{tsoNka} "-PL":{he} "-EP":t "-PRF":{aka} "-IRR":e "=CNT.F":{mi} 

! 4.181 
| "inside":{intsoNpoi} "-LOC":{ki} "=ADV":{ra} 
| "there":{ari} 
| "1SG.S":{no} "=be.at":{saik} "-IRR":i "=CNT.F":{mi} 
| "well":{kametsa} 

! 4.182 
| "1SG.S":{no} "=want":{niNt} "-EP":{tz} "-REAL":i 
| "1SG.S":{no} "=IRR":N "-die":{kam} "-IRR":e "=CNT.F":{mi} 

! 4.183 
| "3m.A":i "=say":{kaNt} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} 
| "grandma":{isha} 
| "2S":{pi} "=IRR":N "-give":{pinat} "-IRR":{ia} "=CNT.F":{mi} 
| "I":{naari} 

! 4.184 
| "3m.S":i "=say":{kaNt} "-EP":{tz} "-REAL":i 
| "come.on":{tsame} "=EMPH":{tya} "=CNT.F":{mi} 

! 4.185 
| "NEG.REAL":{te} 
| "be.much":{osheki} "-EP":t "-IRR":e 
| "3m.poss":i "=meat":{vatsa} 
| "3m.poss":i "=thigh":{pori} "-LOC":{ki} 
| "deer":{maniro} 
| "because":{tema} "=EMPH":{kya} 
| "3m.A":i "=cut":{tot} "-PROG":{atz} "-REAL":i "=3n.m.O":{ro} 
| "3m.poss":i "=flesh":{vatsa} 
| "before":{pairani} 

! 4.186 
| "before":{pairani} 
| "now":{ironyaaka} 
| "3m.A":i "=much":{sheki} "-EP":t "-APPL.REAS":{aNt} "-PRF":{ak} "-REAL":a "=REL":{ri} 
| "hawk":{oovero} 
| "because":{kama} 
| "warriors":{ivayetziri} 
| "1PL.poss":a "=fellowman":{shaniNka} "-PL":{paye} 
| "3m.S":i "=identify.as.a.witch":{itamatzi} "-EP":t "-DIR":{av} "-PRF":{ak} "-PL":{aiy} "-REAL":e "=OPT":{ta} 

! 4.187 
| "because":{tema} 
| "earth":{kipatsi} 
| "1PL.S":a "=be":{na} "-REAL":{tz-i} ! REVISED 
| "earth":{kipatsi} 
| "1PL.S":a "=IRR":N "-return":{piy} "-DIR":{an} "-REGR":{ah} "-IRR":e 

! 4.188 
| "CONN":{ikaNta} 
| "now":{ironyaaka} 
| "3m.A":i "=get.upset.with-IMP.P-EP-PRF-REAL=3m.O" 
| "3m.A":i "=say":{kaNt} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "person’s.name":{Navireri} 

! 4.189 
| "CONN":{okaNta} 
| "rocky.place":{oteNkanaki} "=DEM":{ra} 
| "1SG.A":{no} "=want":{niNt} "-REAL":{tz} "=3n.m.O":{i=ro} ! REVISED 
| "1SG.A":{no} "=IRR":N "-plant":{paNki} "-EP":t "-IRR":e 
| "cedar.tree":{saNtari} 

! 4.190 
| "3m.A":y "=abandon":{ook} "-IMP.P":{ai} "-EP":t "-DIR":{an} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "he":{irirori} 
| "3m.S":i "=disobey":{piyatsa} "-EP":t "-REAL":a 

! 4.191 
| "later":{ponya} 
| "3m.A":i "=bathe":{kaa} "-EP":t "-IMP.P":{ai} "-EP":t "-PRF":{ak} "-IRR":e "=3n.m.O":{ro} 
| "bejuco":{poNkaro} 
| "3n.m.S":o "=get.fat":{vatsa} "-EP":t "-APPL.REAS":{aNt} "-DIR":{an} "-PRF":{ak} "-IRR":{ia} "=REL":{ri} 

! 4.192 
| "1SG.A":n "=make":{aNt} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} 
| "1SG.poss":{no} "=bag":{volsa} "-poss":{te} "-PL":{paye} 
| "1PL.S":a "=IRR":N "-fill":{tet} "-APPL.REAS":{aNt} "-IRR":{ia} "=REL":{ri} 
| "WH":{paita} "=COND":{rika} "-PL":{paye} 
| "2S":{pi} "=IRR":N "-fill":{tet} "-IRR":e "=REL":{ri} 

! 4.193 
| "1SG.A":n "=repeat":{aNpi} "-EP":t "-INS":{aNt} "-REAL":a "=3n.m.O":{ro} 
| "3n.m.S":o "=IRR":N "=be.good":{kameetsa} "-EP":t "-APPL.REAS":{aNt} "-IRR":{ia} "=REL":{ri} 

! 4.194 
| "3n.m.S":o "=grow":{shitov} "-DIR":{an} "-REGR":{ah} "-IRR":e "=OPT":{ta} 
| "other":{pashini} 
| "good":{kametsa} 
| "new":{ovakerari} 
| "3n.m.poss":o "=hair":{ishi} 
| "NEG.IRR":{airo} "=OPT":{ta} 
| "3n.m.S":o "=be.old":{kiNkivarotzi} "-EP":t "-APPL.REAS":{aNt} "-REGR":{ah} "-REAL":a 
| "3n.m.S":o "=be.white":{kitamarotzi} "-EP":t "-APPL.REAS":{aNt} "-REGR":{ah} "-REAL":a 

! 4.195 
| "now":{ironyaaka} 
| "arrive":arii "-EP":t "-DIR":{ap} "-REGR":{ah} "-REAL":a 
| "day":{kitaiteri} 
| "3n.m.S":o "=IRR":N "-happen":{kaNt} "-IRR":{ia} 
| "3n.m.A":o "=leave":{shitov} "-APPL.REAS":{aNt} "-REGR":{ah} "-IRR":{ia} "=REL":{ri} 
| "woman":{kooya} "=DEM":{ra} 

! 4.196 
| "3m.A":y "=gather":{apoto} "-PL":{he} "-EP":t "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "all":{maaroni} 
| "3n.m.S":o "=happen":{kaNt} "-REAL":a 
| "3m.A":y "=work":{aNtavai} "-EP":t "-CAUS":{ak} "-APPL.REAS":{aNt} "-IRR":{ia} "=3m.O":{ri} "=REL":{ri} 

! 4.197 
| "3m.A":i "=stick":{sat} "-IMP.P":{ai} "-EP":t "-DIR":{av} "-PRF":{ak} "-REAL":i "=1SG.O":{na} 
| "3n.m.S":o "=IRR":N "-happen":{kaNt} "-IRR":{ia} 
| "NEG.IRR":{airo} 
| "3n.m.S":o "=feel.pain":{katsik} "-APPL.REAS":{aNt} "-REAL":a 

! 4.198 
| "3n.m.S":o "=IRR":N "-have":{tzim} "-PROG":{aty} "-IRR":e 
| "1PL.A":a "=IRR":N "-call":{kaim} "-CAUS":{ak} "-APPL.REAS":{aNt} "-IRR":e "=3m.O":{ri} 
| "3m.poss":{ir} "=father":{iri} 
| "3n.m.S":o "=IRR":N "-happen":{kaNt} "-IRR":{ia} "=EMPH":{kya} 
| "all":{maaroni} 
| "1PL.A":a "=fix":{vitsik} "-REGR":{ah} "-IRR":e "=3n.m.O":{ro} 
| "well":{kameetsa} 

! 4.199 
| "3n.m.A":o "=put":v "-APPL.INT":{ashi} "-EP":t "-PROG":{aty} "-REAL":a "=3n.m.O":{ro} 
| "3n.m.poss":o "=scarf":{vaanyo} "-poss":{te} 
| "NEG.IRR":{airo} 
| "3n.m.S":o "=appear":{konyaa} "~REAL. EMPH":{tzitzi} 

! 4.200 
| "1PL.S":a "=place":v "-APPL.INT":{ashi} "-EP":t "-PRF":{ak} "-REAL":i "=3n.m.O":{ro} 
| "1PL.A":a "=string":{shintsa} "-EP":t "-PRF":{ak} "-IRR":e "=3m.O":{ri} 

! 4.201 
| "1SG.A":n "=take":a "-EP":{ashi} "-APPL.INT":{tz} "-INCH":{imai} "-EP":t "-REAL":a "=3n.m.O":{ro} 
| "spatula":{inchapataki} 
| "1SG.A=IRR-do-IRR=3n.m.O" 
| "IDEO":{tyak} 
| "IDEO":{tyak} 

! 4.202 
| "1SG.A":{no} "=say":{kaNt} "-APPL.INT":{ashi} "-EP":t "-REAL":a "=3m.O":{ri} 
| "bird.species":{oovero} 
| "2A":p "=take":a "-once":{apaiNt} "-IRR":e "=3n.m.O":{ro} 

! 4.203 
| "3n.m.A":o "=hear":{kem} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "cry":{ir} "-PRF":{ak} "-REAL":a 
| "3n.m.A":o "=run":{shiy} "-APPL.INT":{ashi} "-EP":t "-DIR":{ap} "-PRF":{ak} "-REAL":a "=1SG.O":{na} 

! 4.204 
| "3m.A":i "=go":{hat} "-APPL.INT":{ashi} "-EP":t "-DIR":{an} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "3m.A":i "=see":{ny} "-DIR":{ap} "-PROG":{atz} "-REAL":{i=ri} ! REVISED
| "3m.S":i "=wear.a.cap.on.the.head":{savoina} "-EP":t "-PRF":{ak} "-REAL":a 
| "3m.poss":i "=cushma":{itsa} "-poss":{ri} 

! 4.205 
| "when":{aririka} 
| "1PL":a "=measure":{moNkara} "-EP":t "-PRF":{ak} "-IRR":e "=3n.m.O":{ro} 
| "entire":{maaroni} 
| "advice":{kamenaantsi} "=DEM":{ka} 
| "NEG.IRR":{airo} 
| "1PL.S":a "=return":{piy} "-APPL.INT":{ashi} "-EP":t "-REAL":a 
| "when":{aririka} 
| "1PL.S":a "=go":{ha} "-EP":t "-IRR":e 
| "river":{nihaa} "-LOC":{ki} 
| "take":a "-DIR":{an} "-PRF":{ak} "-IRR":e "=3n.m.O":{ro} 
| "1PL.poss":a "=fish.trap":{shiNperi} 

! 4.206 
| "now":{ironyaaka} 
| "bite":{atsik} "-APPL.INT":{ashi} "-EP":t "-REAL":a "=3n.m.O":{ro} 
| "3n.m.S":o "=fingernail":{shetaki} 
| "IDEO":{takik} 
| "IDEO":{takik} 

! 4.207 
| "NEG.IRR":{airo} 
| "see":{amen} "-APPL.INT":{ashi} "-EP":t "-REAL":a "=3m.O":{ri} 
| "whoever":{niNkarika} 
| "come":{pok} "-STAT":{atsi} "=REL":{ni} 
| "3m.A":i "=IRR":N "-visit":{kivaNt} "=1PL.O":{ai} 
| "1PL.poss":a "=house":{paNko} "-LOC":{ki} 

! 4.208 
| "here":{aka} 
| "1SG.A":{no} "=make":{vetsik} "-APPL.REAS":{aNt} "-EP":a "-DIST":{ye} "-EP":t "-REAL":a "=3n.m.O":{ro} "=REL":{ri} 
| "1SG.A":{no} "=place":v "-APPL.INT":{ashi} "-EP":t "-EP":a "-DIST":{ye} "-REAL":{tzi} "=3n.m.O":{ro} 
| "DEM":{oka} 

! 4.209 
| "then":{oponya} 
| "1SG.A":n "=take":a "-APPL.INT":{ashi} "-EP":t "-PRF":{ak} "-IRR":e "=3n.m.O":{ro} 
| "tree.bark":{patsitaroki} 
| "DEM":{irora} 
| "1SG.A":{no} "=dye":{potsot} "-APPL.REAS":{aNt} "-PRF":{ak} "-REAL":{ia} "=3n.m.O":{ro} "=REL":{ri} 

! 4.210 
| "1SG.S":{no} "=go":{ha} "-EP":t "-PRF":{ak} "-REAL":i 
| "much":{osheki} 
| "place":{naNpitsi} 
| "1SG.S":{no} "=play":{nyaatsa} "-EP":t "-IRR":{ia} 
| "1SG.A":{no} "=be.together":{tsipa} "-EP":t "-PRF":{ak} "-REAL":a "=3m.O":{ri} 
| "black.person":{kisaakiri} "-PL":{paye} 

! 4.211 
| "run":{shiy} "-DIR":{an} "-PRF":{ak} "-REAL":a 
| "other":{pashini} 
| "1SG.poss":{no} "=son":{tomi} 
| "3m.S":y "=look.for":{amin} "-IRR":e 
| "car":{kaaro} 

! 4.212 
| "3m.S":i "=walk":{ken} "-REAL":i 
| "3m.A":i "=teach":{vamet} "-REP":a "-IRR":e "=3m.O":{ri} 
| "3m.S":o "=IRR":N "-happen":{kaNt} "-IRR":{ia} 
| "3m.A":y "=help":{amitako} "-EP":t "-IRR":e "=3m.O":{ri} 
| "person’s.name":{Juan Santos Atahualpa} 

! 4.213 
| "3m.S":i "=come":{pok} "-REAL":i 
| "3m.S":i "=fish":{shima} "-EP":t "-IRR":{ia} 
| "3m.poss":o "=bottom":{tapi} "-LOC":{ki} 

! 4.214 
| "3m.A":i "=go.around":{shoNk} "-DIR":{an} "-REGR":{ah} "-IRR":a "=3n.m.O":{ro} 
| "hill":{otzishi} 
| "3m.S":y "=arrive":{aree} "-EP":t "-APPL.REAS":{aNt} "-REGR":{ah} "-IRR":{ia} "=REL":{ri} 
| "3m.S":i "=be.at":{saik} "-EP":a "-PL":{he} "-EP":{tz} "-REAL":i "=ADV":{Nta} 

! 4.215 
| "3m.A":i "=convert":{pi} "-DIR":{an} "-PRF":{ak} "-REAL":i "=3m.O":{ri} 
| "now":{ironyaaka} 
| "wild.duck":{katari} "-PL":{paye} 
| "FOC":{irotaki} 
| "3m.S":i "=be.much":{sheki} "-EP":t "-APPL.REAS":{aNt} "-REAL":a "=REL":{ri} 
| "wild.duck":{katari} 
| "here":{aka} 

! 4.216 
| "come.on":{tsame} 
| "1PL.A":a "=convert":N "-IRR":{pi} "=3m.O":{i=ri} ! REVISED 
| "curassow":{tsamiri} 
| "much":{osheki} 
| "3m.S":y "=fight":{aNtaNt} "-EP":{tz} "-REAL":i 
| "FOC":{irotaki} 
| "3m.A":i "=convert":{pi} "-APPL.REAS":{aNt} "-PRF":{ak} "-REAL":i "=REL":{ri} 
| "curassow":{tsamiri} 

! 4.217 
| "NEG.IRR":{airo} "=COND":{rika} 
| "3n.m.A":o "=like":{nimo} "-EP":{tz} "-REAL":i "=3n.m.O":{ro} 
| "NEG.IRR":{airo} 
| "3n.m.S":o "=sell":{pimaNta} "-DUR":{vai} "-EP":{tz} "-REAL":i 
| "expect":{ooy} "-REAL":a "=1SG.Osolely":{na} 
| "I":{apaniroini} 
| "FOC":{naaka} 
| "1PL.S":a "=get.upset":{kis} "-REC":{av} "-PRF":{ak} "-APPL.REAS":{aNt} "-HAB":{apiNt} "-REAL":a "=REL":{ri} 

! 4.218 
| "NEG.REAL":{te} 
| "1PL.A":a "=see":{ny} "-IRR":e "=3n.m.O":{ro} 
| "mother":{ina} 
| "3n.m.S":o "=go":{ha} "-EP":t "-PROG":{atz} "-REAL":i 
| "3n.m.S":o "=fish":{shima} "-EP":t "-REAL":a 
| "FOC":{irotaki} 
| "NEG.P":{kaari} 
| "3n.m.A":o "=see":{ny} "-APPL.REAS":{aNt} "-REAL":a "=1SG.O":{na} 
| "1SG.A":{no} "=give.birth":{tzimaNt} "-PRF":{ak} "-REAL":a "=3n.m.O":{ro} "=REL":{ri} 

! 4.219 
| "it’s.necessary":{ontzimatye} 
| "2S":{pi} "=IRR":N "-get.up":{tzin} "-REGR":a "-IRR":e 
| "early":{kapichikitaite} 
| "cross":{anaNkori} "-IRR":e "=2O":{mi} "=APPR":{kari} 
| "death":{kamanitaantsi} 
| "2S":{pi} "=die":{kam} "-IRR":e "=APPR":{kari} 
| "be.quick":{shintsi} "-ADV":{ni} 

! 4.220 
| "2S":{pi} "=go":{ha} "-EP":t "-IRR":e 
| "other.side":{intyatzini} 
| "2A":{pi} "=urinate":{tsiNt} "-APPL":{ako} "-EP":t "-IRR":e "=3m.O":{ri} "=APPR":{kari} 
| "have":{ashi} "-EP":t "-REAL":a "=3n.m.O":{ro} "=REL":{ri} 
| "3m.poss":i "=house":{paNko} 

! 4.221 
| "" 
| "" 
| "" 

! 4.222 
| "" 
| "" 
| "" 

! 4.223 
| "" 
| "" 
| "" 

! 4.224 
| "" 
| "" 
| "" 

! 4.225 
| "" 
| "" 
| "" 

! 4.226 
| "" 
| "" 
| "" 

! 4.227 
| "" 
| "" 
| "" 

! 4.228 
| "" 
| "" 
| "" 

! 4.229 
| "" 
| "" 
| "" 

! 4.330 
| "" 
| "" 
| "" 

! 4.331 
| "" 
| "" 
| "" 

! 4.332 
| "" 
| "" 
| "" 

! 4.333 
| "" 
| "" 
| "" 

! 4.334 
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 

!  
| "" 
| "" 
| "" 
























];
